/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.CardLayout;

/**
 *
 * @author Administrador
 */
public class ComidaPanelMain extends javax.swing.JPanel {
    private ComidaPanelMenu comidaPanelMenu;
    private ComidaPanel comidaPanel;
    private ComidaDietaPanel comidaDietaPanel;
//    private ComidaPanelAdv comidaPanelAdv;
    private CardLayout cardLayout;
    /**
     * Creates new form ComidaPanelMain
     */
    public ComidaPanelMain() {
        initComponents();
        CrearComidaPaneles();
    }
    
    private void CrearComidaPaneles(){
        comidaPanelMenu = new ComidaPanelMenu(this);
        comidaPanel = new ComidaPanel(this);
        comidaDietaPanel = new ComidaDietaPanel(this);
//        comidaPanelAdv = new ComidaPanelAdv(this);
        add(comidaPanelMenu, "comidaMenu");
        add(comidaPanel, "comidaBas");
        add(comidaDietaPanel, "comidaDieta");
//        add(comidaPanelAdv, "comidaAdv");
        cardLayout = (CardLayout) getLayout();
        cardLayout.show(this, "comidaMenu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(30, 30, 30));
        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public ComidaPanelMenu getComidaPanelMenu() {
        return comidaPanelMenu;
    }

    public ComidaPanel getComidaPanel() {
        return comidaPanel;
    }

    public CardLayout getCardLayout() {
        return cardLayout;
    }

}
