/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Entidades.Dieta;
import Entidades.Paciente;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Administrador
 */
public class DetallePacientePanel extends javax.swing.JPanel {
//    private final Dieta dieta;
    private Paciente paciente;
    /**
     * Creates new form DetalleDieta
     */
    public DetallePacientePanel(Paciente paciente){ //(Dieta dieta) {
        initComponents();
//        this.dieta = dieta;
        this.paciente = paciente; //dieta.getPaciente();
        cargarDetallePaciente();
    }

    private void cargarDetallePaciente(){
        jLabelCodPacienteData.setText(""+paciente.getIdPaciente());
        jLabelDocumentoData.setText(paciente.getDni());
        jLabelApellidoData.setText(""+paciente.getAltura());
        jLabelNombreData.setText(paciente.getNombre());
        jLabelDomicilioData.setText(paciente.getDomicilio());
        jLabelTelefonoData.setText(paciente.getTelefonoFijo());
        jLabelCelularData.setText(paciente.getCelular());
        jLabelEmailData.setText(paciente.getMail());
        jLabelAlturaPacDAta.setText(""+paciente.getAltura());
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        jLabelFechaNacData.setText(paciente.getFechaNac().format(formatter));
        jLabelEstadoData.setText(paciente.isEstado()?"Activo":"Inactivo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodPaciente = new javax.swing.JLabel();
        jLabelCodPacienteData = new javax.swing.JLabel();
        jLabelDocumento = new javax.swing.JLabel();
        jLabelDocumentoData = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelApellidoData = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelNombreData = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelTelefonoData = new javax.swing.JLabel();
        jLabelCelular = new javax.swing.JLabel();
        jLabelCelularData = new javax.swing.JLabel();
        jLabelFechaNac = new javax.swing.JLabel();
        jLabelFechaNacData = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelEstadoData = new javax.swing.JLabel();
        jLabelDomicilio = new javax.swing.JLabel();
        jLabelDomicilioData = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelEmailData = new javax.swing.JLabel();
        jLabelAlturaPac = new javax.swing.JLabel();
        jLabelAlturaPacDAta = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelCodPaciente.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelCodPaciente.setText("Cod. Paciente:");
        jLabelCodPaciente.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelCodPacienteData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelCodPacienteData.setText("TEXTO1");
        jLabelCodPacienteData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelDocumento.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelDocumento.setText("Documento:");
        jLabelDocumento.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelDocumentoData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelDocumentoData.setText("TEXTO2");
        jLabelDocumentoData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelApellido.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelApellido.setText("Apellido");
        jLabelApellido.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelApellidoData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelApellidoData.setText("TEXTO3");
        jLabelApellidoData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelNombre.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelNombre.setText("Nombre:");
        jLabelNombre.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelNombreData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelNombreData.setText("TEXTO4");
        jLabelNombreData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelTelefono.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelTelefono.setText("Telefono:");
        jLabelTelefono.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelTelefonoData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelTelefonoData.setText("TEXTO5");
        jLabelTelefonoData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelCelular.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelCelular.setText("Celular:");
        jLabelCelular.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelCelularData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelCelularData.setText("TEXTO6");
        jLabelCelularData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelFechaNac.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelFechaNac.setText("Fecha Nac.:");
        jLabelFechaNac.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelFechaNacData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelFechaNacData.setText("TEXTO7");
        jLabelFechaNacData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelEstado.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelEstado.setText("Estado:");
        jLabelEstado.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelEstadoData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelEstadoData.setText("TEXTO8");
        jLabelEstadoData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelDomicilio.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelDomicilio.setText("Domicilio:");
        jLabelDomicilio.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelDomicilioData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelDomicilioData.setText("TEXTO3");
        jLabelDomicilioData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelEmail.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelEmail.setText("Email:");
        jLabelEmail.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelEmailData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelEmailData.setText("TEXTO5");
        jLabelEmailData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelAlturaPac.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelAlturaPac.setText("Altura Pac.:");
        jLabelAlturaPac.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelAlturaPacDAta.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelAlturaPacDAta.setText("TEXTO6");
        jLabelAlturaPacDAta.setPreferredSize(new java.awt.Dimension(125, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelEmailData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jLabelDomicilioData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCodPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabelCodPacienteData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabelApellidoData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabelTelefonoData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabelFechaNacData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabelDocumentoData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabelNombreData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabelCelularData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabelEstadoData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelAlturaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabelAlturaPacDAta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCodPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodPacienteData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDocumentoData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelApellidoData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDomicilioData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTelefonoData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCelularData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmailData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlturaPac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlturaPacDAta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaNacData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstadoData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(5, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAlturaPac;
    private javax.swing.JLabel jLabelAlturaPacDAta;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelApellidoData;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelCelularData;
    private javax.swing.JLabel jLabelCodPaciente;
    private javax.swing.JLabel jLabelCodPacienteData;
    private javax.swing.JLabel jLabelDocumento;
    private javax.swing.JLabel jLabelDocumentoData;
    private javax.swing.JLabel jLabelDomicilio;
    private javax.swing.JLabel jLabelDomicilioData;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmailData;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelEstadoData;
    private javax.swing.JLabel jLabelFechaNac;
    private javax.swing.JLabel jLabelFechaNacData;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreData;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTelefonoData;
    // End of variables declaration//GEN-END:variables
}
