/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Entidades.Dieta;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Administrador
 */
public class DetalleDietaPanel extends javax.swing.JPanel {
    private Dieta dieta;
    /**
     * Creates new form DetalleDieta
     */
    public DetalleDietaPanel(Dieta dieta) {
        initComponents();
        this.dieta = dieta;
        cargarDetalleDieta();
    }

    private void cargarDetalleDieta(){
        jLabelCodDietaData.setText(""+dieta.getIdDieta());
        jLabelDietaNombreData.setText(dieta.getNombre());
        jLabelPesoInicialData.setText(""+dieta.getPesoInicial());
        jLabelPesoActualData.setText(""+dieta.getPesoActual());
        //jLabelRPesoReqData.setText(llamar metodo);
        jLabelEstadoData.setText((dieta.isEstado())?"En Curso":"Terminada");
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        jLabelFechaInicialData.setText(dieta.getFechaInicio().format(formatter));
        jLabelFechaActualData.setText(dieta.getFechaFinal().format(formatter));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCodDieta = new javax.swing.JLabel();
        jLabelCodDietaData = new javax.swing.JLabel();
        jLabelDietaNombre = new javax.swing.JLabel();
        jLabelDietaNombreData = new javax.swing.JLabel();
        jLabelPesoInicial = new javax.swing.JLabel();
        jLabelPesoInicialData = new javax.swing.JLabel();
        jLabelPesoActual = new javax.swing.JLabel();
        jLabelPesoActualData = new javax.swing.JLabel();
        jLabelRPesoReq = new javax.swing.JLabel();
        jLabelRPesoReqData = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelEstadoData = new javax.swing.JLabel();
        jLabelFechaInicial = new javax.swing.JLabel();
        jLabelFechaInicialData = new javax.swing.JLabel();
        jLabelFechaActual = new javax.swing.JLabel();
        jLabelFechaActualData = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelCodDieta.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelCodDieta.setText("Cod. Dieta:");
        jLabelCodDieta.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelCodDietaData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelCodDietaData.setText("TEXTO1");
        jLabelCodDietaData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelDietaNombre.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelDietaNombre.setText("Dieta Nombre:");
        jLabelDietaNombre.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelDietaNombreData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelDietaNombreData.setText("TEXTO2");
        jLabelDietaNombreData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelPesoInicial.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelPesoInicial.setText("Peso Inicial:");
        jLabelPesoInicial.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelPesoInicialData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelPesoInicialData.setText("TEXTO3");
        jLabelPesoInicialData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelPesoActual.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelPesoActual.setText("Pesa Actual:");
        jLabelPesoActual.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelPesoActualData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelPesoActualData.setText("TEXTO4");
        jLabelPesoActualData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelRPesoReq.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelRPesoReq.setText("Rango Peso Req.:");
        jLabelRPesoReq.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelRPesoReqData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelRPesoReqData.setText("TEXTO5");
        jLabelRPesoReqData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelEstado.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelEstado.setText("Estado:");
        jLabelEstado.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelEstadoData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelEstadoData.setText("TEXTO6");
        jLabelEstadoData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelFechaInicial.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelFechaInicial.setText("Fecha Inicial:");
        jLabelFechaInicial.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelFechaInicialData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelFechaInicialData.setText("TEXTO7");
        jLabelFechaInicialData.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelFechaActual.setFont(new java.awt.Font("JetBrains Mono NL ExtraLight", 1, 14)); // NOI18N
        jLabelFechaActual.setText("Fecha Actual:");
        jLabelFechaActual.setPreferredSize(new java.awt.Dimension(125, 30));

        jLabelFechaActualData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N
        jLabelFechaActualData.setText("TEXTO8");
        jLabelFechaActualData.setPreferredSize(new java.awt.Dimension(125, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCodDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabelCodDietaData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabelPesoInicialData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelRPesoReq, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabelRPesoReqData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabelFechaInicialData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDietaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelDietaNombreData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPesoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelPesoActualData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelEstadoData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelFechaActualData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCodDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCodDietaData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDietaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDietaNombreData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPesoInicialData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPesoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPesoActualData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelRPesoReq, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRPesoReqData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstadoData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaInicialData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaActualData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCodDieta;
    private javax.swing.JLabel jLabelCodDietaData;
    private javax.swing.JLabel jLabelDietaNombre;
    private javax.swing.JLabel jLabelDietaNombreData;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelEstadoData;
    private javax.swing.JLabel jLabelFechaActual;
    private javax.swing.JLabel jLabelFechaActualData;
    private javax.swing.JLabel jLabelFechaInicial;
    private javax.swing.JLabel jLabelFechaInicialData;
    private javax.swing.JLabel jLabelPesoActual;
    private javax.swing.JLabel jLabelPesoActualData;
    private javax.swing.JLabel jLabelPesoInicial;
    private javax.swing.JLabel jLabelPesoInicialData;
    private javax.swing.JLabel jLabelRPesoReq;
    private javax.swing.JLabel jLabelRPesoReqData;
    // End of variables declaration//GEN-END:variables
}
