/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.CardLayout;

/**
 *
 * @author Administrador
 */
public class DietaPanelMain extends javax.swing.JPanel {

    private DietaPanelMenu dietaPanelMenu;
    private DietaPanel dietaPanel;
    private DietaPacientePanelAdv dietaPacientePanelAdv;
    private CardLayout cardLayout;

    /**
     * Creates new form DietaPanelMain
     */
    public DietaPanelMain() {
        initComponents();
        CrearDietaPaneles();
    }
    
    private void CrearDietaPaneles(){
        dietaPanelMenu = new DietaPanelMenu(this);
        dietaPanel = new DietaPanel(this);
        dietaPacientePanelAdv = new DietaPacientePanelAdv(this);
        add(dietaPanelMenu, "dietaMenu");
        add(dietaPanel, "dietaBas");
        add(dietaPacientePanelAdv, "dietaPacienteAdv");
        cardLayout = (CardLayout) getLayout();
        cardLayout.show(this, "dietaMenu");
        
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(51, 255, 51));
        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    public DietaPanelMenu getDietaPanelMenu() {
        return dietaPanelMenu;
    }

    public DietaPanel getDietaPanel() {
        return dietaPanel;
    }

    public DietaPacientePanelAdv getDietaPacientePanelAdv() {
        return dietaPacientePanelAdv;
    }

    public CardLayout getCardLayout() {
        return cardLayout;
    }

}
