/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.ControladorDieta;
import Entidades.Paciente;
import com.toedter.calendar.JDateChooser;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Administrador
 */
public class DietaPanel extends java.awt.Panel {
    private final DietaPanelMain dietaPanelMain;
    private final ControladorDieta controladorDieta;
    private int desdePanel;

    /**
     * Creates new form DietaPanel
     */
    public DietaPanel(DietaPanelMain dietaPanelMain) {
        initComponents();
        this.dietaPanelMain = dietaPanelMain;
        boxModel = new DefaultComboBoxModel();
        controladorDieta = new ControladorDieta(this);
        desdePanel = 0;
    }
    
    private void cargarBoxModel(){
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPaciente = new javax.swing.JPanel();
        jPanelPacienteForm = new javax.swing.JPanel();
        jLabelCodDieta = new javax.swing.JLabel();
        jLabelDietaNombre = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jTextFieldDietaNombre = new javax.swing.JTextField();
        jTextFieldCodDieta = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jCheckBoxEstado = new javax.swing.JCheckBox();
        jLabelKg1 = new javax.swing.JLabel();
        jTextFieldPesoInicial = new javax.swing.JTextField();
        jLabelPesoActual = new javax.swing.JLabel();
        jTextFieldPesoActual = new javax.swing.JTextField();
        jLabelRPesoRequerido = new javax.swing.JLabel();
        jLabelDniData = new javax.swing.JLabel();
        jDateChooserFechaInicio = new com.toedter.calendar.JDateChooser();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelFechaFinal = new javax.swing.JLabel();
        jDateChooserFechaFinal = new com.toedter.calendar.JDateChooser();
        jLabelRPesoRequeridoData = new javax.swing.JLabel();
        jLabelPesoInicial = new javax.swing.JLabel();
        jLabelKg2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelFechaInicio = new javax.swing.JLabel();
        jLabelDni = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelApellidoData = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelNombreData = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBoxPaciente = new javax.swing.JComboBox<>();
        jButtonLimpiarForm = new javax.swing.JButton();
        jPanelPacienteTitulo = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelVolver = new javax.swing.JLabel();
        jPanelPacienteBotones = new javax.swing.JPanel();
        jButtonNuevo = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        setBackground(java.awt.Color.darkGray);

        jPanelPaciente.setPreferredSize(new java.awt.Dimension(640, 480));
        jPanelPaciente.setLayout(new java.awt.BorderLayout());

        jLabelCodDieta.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelCodDieta.setText("Cod. Dieta:");
        jLabelCodDieta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelDietaNombre.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelDietaNombre.setText("Dieta Nombre:");
        jLabelDietaNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelEstado.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelEstado.setText("Estado:");
        jLabelEstado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldDietaNombre.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jTextFieldDietaNombre.setPreferredSize(new java.awt.Dimension(200, 30));

        jTextFieldCodDieta.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jTextFieldCodDieta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCodDieta.setMinimumSize(new java.awt.Dimension(14, 30));
        jTextFieldCodDieta.setPreferredSize(new java.awt.Dimension(200, 30));

        jButtonBuscar.setBackground(new java.awt.Color(30, 30, 30));
        jButtonBuscar.setToolTipText("Buscar Por DNI");
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setContentAreaFilled(false);
        jButtonBuscar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonBuscar.setMaximumSize(new java.awt.Dimension(5000, 5000));
        jButtonBuscar.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonBuscar.setRequestFocusEnabled(false);
        jButtonBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonBuscarFocusLost(evt);
            }
        });
        jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonBuscarMousePressed(evt);
            }
        });
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jButtonBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButtonBuscarKeyTyped(evt);
            }
        });

        jCheckBoxEstado.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 14)); // NOI18N
        jCheckBoxEstado.setText("En Curso");
        jCheckBoxEstado.setPreferredSize(new java.awt.Dimension(150, 36));
        jCheckBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEstadoActionPerformed(evt);
            }
        });

        jLabelKg1.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelKg1.setText("KG.");
        jLabelKg1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldPesoInicial.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jTextFieldPesoInicial.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabelPesoActual.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelPesoActual.setText("Peso Actual:");
        jLabelPesoActual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldPesoActual.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jTextFieldPesoActual.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabelRPesoRequerido.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelRPesoRequerido.setText("Rango Peso Requerido:");
        jLabelRPesoRequerido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelRPesoRequerido.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabelDniData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelDniData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelDniData.setPreferredSize(new java.awt.Dimension(300, 25));

        jDateChooserFechaInicio.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 18)); // NOI18N

        jLabelFechaFinal.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelFechaFinal.setText("Fecha Final:");
        jLabelFechaFinal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelFechaFinal.setPreferredSize(new java.awt.Dimension(300, 25));

        jDateChooserFechaFinal.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 18)); // NOI18N
        jDateChooserFechaFinal.setPreferredSize(new java.awt.Dimension(200, 29));

        jLabelRPesoRequeridoData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 16)); // NOI18N

        jLabelPesoInicial.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelPesoInicial.setText("Peso Inicial:");
        jLabelPesoInicial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelKg2.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelKg2.setText("KG.");
        jLabelKg2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("JetBrains Mono NL Thin", 1, 18)); // NOI18N
        jLabel4.setText("Paciente:");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 36));

        jLabelFechaInicio.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelFechaInicio.setText("Fecha Inicio:");
        jLabelFechaInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelFechaInicio.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabelDni.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelDni.setText("Documento:");
        jLabelDni.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelDni.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabelApellido.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelApellido.setText("Apellido:");
        jLabelApellido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelApellido.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabelApellidoData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelApellidoData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelApellidoData.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabelNombre.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombre:");
        jLabelNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelNombre.setPreferredSize(new java.awt.Dimension(300, 25));

        jLabelNombreData.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelNombreData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelNombreData.setPreferredSize(new java.awt.Dimension(300, 25));

        boxModel = new DefaultComboBoxModel();
        jComboBoxPaciente.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jComboBoxPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPacienteActionPerformed(evt);
            }
        });

        jButtonLimpiarForm.setBackground(new java.awt.Color(30, 30, 30));
        jButtonLimpiarForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Broom48px.png"))); // NOI18N
        jButtonLimpiarForm.setBorder(null);
        jButtonLimpiarForm.setContentAreaFilled(false);
        jButtonLimpiarForm.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLimpiarForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPacienteFormLayout = new javax.swing.GroupLayout(jPanelPacienteForm);
        jPanelPacienteForm.setLayout(jPanelPacienteFormLayout);
        jPanelPacienteFormLayout.setHorizontalGroup(
            jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPacienteFormLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabelCodDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCodDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButtonLimpiarForm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 34, Short.MAX_VALUE)
                .addComponent(jLabelDietaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDietaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanelPacienteFormLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPacienteFormLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPacienteFormLayout.createSequentialGroup()
                        .addComponent(jLabelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelApellidoData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDni, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDniData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(jPanelPacienteFormLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator3)
                .addContainerGap())
            .addGroup(jPanelPacienteFormLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPacienteFormLayout.createSequentialGroup()
                        .addComponent(jLabelPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelKg1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPacienteFormLayout.createSequentialGroup()
                        .addComponent(jLabelFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPacienteFormLayout.createSequentialGroup()
                        .addComponent(jLabelRPesoRequerido, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelRPesoRequeridoData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPacienteFormLayout.createSequentialGroup()
                                .addComponent(jLabelFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPacienteFormLayout.createSequentialGroup()
                                .addComponent(jLabelPesoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPesoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelKg2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelPacienteFormLayout.createSequentialGroup()
                                .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
        );
        jPanelPacienteFormLayout.setVerticalGroup(
            jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacienteFormLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelCodDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCodDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDietaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDietaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonLimpiarForm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelDniData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelDni, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelApellidoData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPacienteFormLayout.createSequentialGroup()
                        .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelKg1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPesoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPesoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPesoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelKg2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelRPesoRequerido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelRPesoRequeridoData, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCheckBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanelPaciente.add(jPanelPacienteForm, java.awt.BorderLayout.CENTER);

        jPanelPacienteTitulo.setBackground(new java.awt.Color(39, 54, 64));

        jLabelTitulo.setFont(new java.awt.Font("JetBrains Mono NL ExtraBold", 1, 30)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Dieta");

        jLabelVolver.setFont(new java.awt.Font("JetBrains Mono NL Thin", 1, 12)); // NOI18N
        jLabelVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BackArrow48px.png"))); // NOI18N
        jLabelVolver.setText("Volver");
        jLabelVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelPacienteTituloLayout = new javax.swing.GroupLayout(jPanelPacienteTitulo);
        jPanelPacienteTitulo.setLayout(jPanelPacienteTituloLayout);
        jPanelPacienteTituloLayout.setHorizontalGroup(
            jPanelPacienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacienteTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(674, Short.MAX_VALUE))
        );
        jPanelPacienteTituloLayout.setVerticalGroup(
            jPanelPacienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacienteTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPacienteTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanelPaciente.add(jPanelPacienteTitulo, java.awt.BorderLayout.NORTH);

        jButtonNuevo.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 14)); // NOI18N
        jButtonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add properties48px.png"))); // NOI18N
        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.setToolTipText("Nueva Dieta");
        jButtonNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButtonNuevo.setMaximumSize(new java.awt.Dimension(200, 40));
        jButtonNuevo.setMinimumSize(new java.awt.Dimension(75, 30));
        jButtonNuevo.setPreferredSize(new java.awt.Dimension(75, 35));
        jButtonNuevo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonNuevoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonNuevoFocusLost(evt);
            }
        });
        jButtonNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonNuevoMouseExited(evt);
            }
        });
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonGuardar.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 14)); // NOI18N
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setToolTipText("Guardar Dieta");
        jButtonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButtonGuardar.setMaximumSize(new java.awt.Dimension(200, 40));
        jButtonGuardar.setMinimumSize(new java.awt.Dimension(93, 30));
        jButtonGuardar.setPreferredSize(new java.awt.Dimension(93, 35));
        jButtonGuardar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonGuardarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonGuardarFocusLost(evt);
            }
        });
        jButtonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonGuardarMouseExited(evt);
            }
        });
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 14)); // NOI18N
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CloseWindow.png"))); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setToolTipText("Salir del Programa");
        jButtonSalir.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jButtonSalir.setMaximumSize(new java.awt.Dimension(200, 40));
        jButtonSalir.setMinimumSize(new java.awt.Dimension(75, 30));
        jButtonSalir.setPreferredSize(new java.awt.Dimension(75, 35));
        jButtonSalir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonSalirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonSalirFocusLost(evt);
            }
        });
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseExited(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPacienteBotonesLayout = new javax.swing.GroupLayout(jPanelPacienteBotones);
        jPanelPacienteBotones.setLayout(jPanelPacienteBotonesLayout);
        jPanelPacienteBotonesLayout.setHorizontalGroup(
            jPanelPacienteBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacienteBotonesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanelPacienteBotonesLayout.setVerticalGroup(
            jPanelPacienteBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacienteBotonesLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelPacienteBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPacienteBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelPaciente.add(jPanelPacienteBotones, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanelPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNuevoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonNuevoFocusGained
        controladorDieta.buttonNuevoFocusGained(evt);
    }//GEN-LAST:event_jButtonNuevoFocusGained

    private void jButtonNuevoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonNuevoFocusLost
        controladorDieta.buttonNuevoFocusLost(evt);
    }//GEN-LAST:event_jButtonNuevoFocusLost

    private void jButtonNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNuevoMouseEntered
        controladorDieta.buttonNuevoMouseEntered(evt);
    }//GEN-LAST:event_jButtonNuevoMouseEntered

    private void jButtonNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNuevoMouseExited
        controladorDieta.buttonNuevoMouseExited(evt);
    }//GEN-LAST:event_jButtonNuevoMouseExited

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        controladorDieta.nuevoDietaActionPerformed(evt);
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonGuardarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonGuardarFocusGained
        controladorDieta.buttonGuardarFocusGained(evt);
    }//GEN-LAST:event_jButtonGuardarFocusGained

    private void jButtonGuardarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonGuardarFocusLost
        controladorDieta.buttonGuardarFocusLost(evt);
    }//GEN-LAST:event_jButtonGuardarFocusLost

    private void jButtonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarMouseEntered
        controladorDieta.buttonGuardarMouseEntered(evt);
    }//GEN-LAST:event_jButtonGuardarMouseEntered

    private void jButtonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonGuardarMouseExited
        controladorDieta.buttonGuardarMouseExited(evt);
    }//GEN-LAST:event_jButtonGuardarMouseExited

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        controladorDieta.guardarDietaActionPerformed(evt);
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonSalirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonSalirFocusGained
        controladorDieta.buttonSalirFocusGained(evt);
    }//GEN-LAST:event_jButtonSalirFocusGained

    private void jButtonSalirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonSalirFocusLost
        controladorDieta.buttonSalirFocusLost(evt);
    }//GEN-LAST:event_jButtonSalirFocusLost

    private void jButtonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseEntered
        controladorDieta.buttonSalirMouseEntered(evt);
    }//GEN-LAST:event_jButtonSalirMouseEntered

    private void jButtonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseExited
        controladorDieta.buttonSalirMouseExited(evt);
    }//GEN-LAST:event_jButtonSalirMouseExited

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        controladorDieta.salirDietaActionPerformed(evt);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonBuscarFocusGained
        controladorDieta.buttonBuscarFocusGained(evt);
    }//GEN-LAST:event_jButtonBuscarFocusGained

    private void jButtonBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonBuscarFocusLost
        controladorDieta.buttonBuscarFocusLost(evt);
    }//GEN-LAST:event_jButtonBuscarFocusLost

    private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseClicked
        controladorDieta.buttonBuscarMouseClicked(evt);
    }//GEN-LAST:event_jButtonBuscarMouseClicked

    private void jButtonBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseEntered
        controladorDieta.buttonBuscarMouseEntered(evt);
    }//GEN-LAST:event_jButtonBuscarMouseEntered

    private void jButtonBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseExited
        controladorDieta.buttonBuscarMouseExited(evt);
    }//GEN-LAST:event_jButtonBuscarMouseExited

    private void jButtonBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMousePressed
        controladorDieta.buttonBuscarMousePressed(evt);
    }//GEN-LAST:event_jButtonBuscarMousePressed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        controladorDieta.buttonBuscarActionPerformed(evt);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonBuscarKeyReleased
        controladorDieta.buttonBuscarKeyReleased(evt);
    }//GEN-LAST:event_jButtonBuscarKeyReleased

    private void jButtonBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonBuscarKeyTyped
        controladorDieta.buttonBuscarKeyTyped(evt);
    }//GEN-LAST:event_jButtonBuscarKeyTyped

    private void jCheckBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEstadoActionPerformed
        controladorDieta.checkBoxEstadoActionPerformed(evt);
    }//GEN-LAST:event_jCheckBoxEstadoActionPerformed

    private void jButtonLimpiarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarFormActionPerformed
        controladorDieta.ButtonLimpiarFormActionPerformed(evt);
    }//GEN-LAST:event_jButtonLimpiarFormActionPerformed

    private void jLabelVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVolverMouseClicked
        controladorDieta.labelVolverMouseClicked(evt);
    }//GEN-LAST:event_jLabelVolverMouseClicked

    private void jComboBoxPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPacienteActionPerformed
        controladorDieta.comboBoxPacienteActionPerformed(evt);
    }//GEN-LAST:event_jComboBoxPacienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiarForm;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JCheckBox jCheckBoxEstado;
    private javax.swing.JComboBox<Paciente> jComboBoxPaciente;
    private DefaultComboBoxModel boxModel;
    private com.toedter.calendar.JDateChooser jDateChooserFechaFinal;
    private com.toedter.calendar.JDateChooser jDateChooserFechaInicio;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelApellidoData;
    private javax.swing.JLabel jLabelCodDieta;
    private javax.swing.JLabel jLabelDietaNombre;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelDniData;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelFechaFinal;
    private javax.swing.JLabel jLabelFechaInicio;
    private javax.swing.JLabel jLabelKg1;
    private javax.swing.JLabel jLabelKg2;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombreData;
    private javax.swing.JLabel jLabelPesoActual;
    private javax.swing.JLabel jLabelPesoInicial;
    private javax.swing.JLabel jLabelRPesoRequerido;
    private javax.swing.JLabel jLabelRPesoRequeridoData;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelVolver;
    private javax.swing.JPanel jPanelPaciente;
    private javax.swing.JPanel jPanelPacienteBotones;
    private javax.swing.JPanel jPanelPacienteForm;
    private javax.swing.JPanel jPanelPacienteTitulo;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextFieldCodDieta;
    private javax.swing.JTextField jTextFieldDietaNombre;
    private javax.swing.JTextField jTextFieldPesoActual;
    private javax.swing.JTextField jTextFieldPesoInicial;
    // End of variables declaration//GEN-END:variables
    
    public JButton getjButtonLimpiarForm() {
        return jButtonLimpiarForm;
    }
    
    public JButton getjButtonBuscar() {
        return jButtonBuscar;
    }

//    public JButton getjButtonEliminar() {
//        return jButtonEliminar;
//    }

    public JButton getjButtonGuardar() {
        return jButtonGuardar;
    }

    public JButton getjButtonNuevo() {
        return jButtonNuevo;
    }

    public JButton getjButtonSalir() {
        return jButtonSalir;
    }

    public JCheckBox getjCheckBoxEstado() {
        return jCheckBoxEstado;
    }

    public JDateChooser getjDateChooserFechaFinal() {
        return jDateChooserFechaFinal;
    }

    public JDateChooser getjDateChooserFechaInicio() {
        return jDateChooserFechaInicio;
    }

    public JLabel getjLabelCodDieta() {
        return jLabelCodDieta;
    }
    
    public JLabel getjLabelVolver() {
        return jLabelVolver;
    }
    
    public JLabel getjLabelDietaNombre() {
        return jLabelDietaNombre;
    }

    public JLabel getjLabelDniData() {
        return jLabelDniData;
    }
    
    public JLabel getjLabelApellidoData() {
        return jLabelApellidoData;
    }
    
    public JLabel getjLabelNombreData() {
        return jLabelNombreData;
    }

    public JLabel getjLabelFechaFinal() {
        return jLabelFechaFinal;
    }

    public JLabel getjLabelFechaInicio() {
        return jLabelFechaInicio;
    }
    
    public JLabel getjLabelPesoInicial() {
        return jLabelPesoInicial;
    }

    public JLabel getjLabelKg1() {
        return jLabelKg1;
    }
    
    public JLabel getjLabelPesoActual() {
        return jLabelPesoActual;
    }

    public JLabel getjLabelKg2() {
        return jLabelKg2;
    }

    public JLabel getjLabelRPesoRequerido() {
        return jLabelRPesoRequerido;
    }

    public JLabel getjLabelRPesoRequeridoData() {
        return jLabelRPesoRequeridoData;
    }

    public JTextField getjTextFieldCodDieta() {
        return jTextFieldCodDieta;
    }

    public JTextField getjTextFieldDietaNombre() {
        return jTextFieldDietaNombre;
    }

    public JTextField getjTextFieldPesoInicial() {
        return jTextFieldPesoInicial;
    }
    
    public JTextField getjTextFieldPesoActual() {
        return jTextFieldPesoActual;
    }

    public DefaultComboBoxModel getBoxModel() {
        return boxModel;
    }

    public JComboBox<Paciente> getjComboBoxPaciente() {
        return jComboBoxPaciente;
    }

    public DietaPanelMain getDietaPanelMain() {
        return dietaPanelMain;
    }

    public int getDesdePanel() {
        return desdePanel;
    }

    public void setDesdePanel(int desdePanel) {
        this.desdePanel = desdePanel;
    }

}
