/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.PacienteData;
import Controladores.ControladorPacientesAdv;
import Entidades.Dieta;
import Entidades.Paciente;
import Vistas.Render.RenderTable;
import com.formdev.flatlaf.extras.components.FlatTriStateCheckBox;
import com.toedter.calendar.JDateChooser;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JTree;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import nutris.Conexion;

/**
 *
 * @author Administrador
 */
public class DietaPacientePanelAdv extends java.awt.Panel {
    private DietaPanelMain dietaPanelMain;
    private ControladorPacientesAdv controladorPacientesAdv;

    /**
     * Creates new form PacientePanelAdv
     */
    public DietaPacientePanelAdv(DietaPanelMain dietaPanelMain) {
        initComponents();
        this.dietaPanelMain = dietaPanelMain;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelForm = new javax.swing.JPanel();
        jPanelDietaPaciente = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonDieta = new javax.swing.JRadioButton();
        jRadioButtonPaciente = new javax.swing.JRadioButton();
        jPanelCardPacienteCard = new javax.swing.JPanel();
        jPanelBusquedaDieta = new javax.swing.JPanel();
        jLabelCodDieta = new javax.swing.JLabel();
        jTextFieldCodDieta = new javax.swing.JTextField();
        jPanelCond1 = new javax.swing.JPanel();
        jPanelCondSOps1 = new javax.swing.JPanel();
        jPanelCondCOps1 = new javax.swing.JPanel();
        jRadioButtonCondY1 = new javax.swing.JRadioButton();
        jRadioButtonCondO1 = new javax.swing.JRadioButton();
        jLabelDietaNombre = new javax.swing.JLabel();
        jTextFieldDietaNombre = new javax.swing.JTextField();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jLabelEstadoDieta = new javax.swing.JLabel();
        flatTriStateCheckBoxEstadoDieta = new com.formdev.flatlaf.extras.components.FlatTriStateCheckBox();
        jLabelRangoPesoRequerido = new javax.swing.JLabel();
        flatTriStateCheckBoxRangoPesoRequerido = new com.formdev.flatlaf.extras.components.FlatTriStateCheckBox();
        jPanelCond2 = new javax.swing.JPanel();
        jPanelCondSOps2 = new javax.swing.JPanel();
        jPanelCondCOps2 = new javax.swing.JPanel();
        jRadioButtonCondY2 = new javax.swing.JRadioButton();
        jRadioButtonCondO2 = new javax.swing.JRadioButton();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        filler10 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        filler11 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jPanelCond3 = new javax.swing.JPanel();
        jPanelCondSOps3 = new javax.swing.JPanel();
        jPanelCondCOps3 = new javax.swing.JPanel();
        jRadioButtonCondY3 = new javax.swing.JRadioButton();
        jRadioButtonCondO3 = new javax.swing.JRadioButton();
        filler13 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jPanelBusquedaPaciente = new javax.swing.JPanel();
        jLabelDni = new javax.swing.JLabel();
        jTextFieldDni = new javax.swing.JTextField();
        jPanelCond4 = new javax.swing.JPanel();
        jPanelCondSOps4 = new javax.swing.JPanel();
        jPanelCondCOps4 = new javax.swing.JPanel();
        jRadioButtonCondY4 = new javax.swing.JRadioButton();
        jRadioButtonCondO4 = new javax.swing.JRadioButton();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        filler12 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        filler14 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jLabelEstado = new javax.swing.JLabel();
        flatTriStateCheckBoxEstado = new com.formdev.flatlaf.extras.components.FlatTriStateCheckBox();
        jPanelCond5 = new javax.swing.JPanel();
        jPanelCondSOps5 = new javax.swing.JPanel();
        jPanelCondCOps5 = new javax.swing.JPanel();
        jRadioButtonCondY5 = new javax.swing.JRadioButton();
        jRadioButtonCondO5 = new javax.swing.JRadioButton();
        filler15 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        filler16 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        filler17 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jPanelCond6 = new javax.swing.JPanel();
        jPanelCondSOps6 = new javax.swing.JPanel();
        jPanelCondCOps6 = new javax.swing.JPanel();
        jRadioButtonCondY6 = new javax.swing.JRadioButton();
        jRadioButtonCondO6 = new javax.swing.JRadioButton();
        filler18 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jPanelDietaCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeDietas = new javax.swing.JTree();
        jPanelDetalles = new javax.swing.JPanel();
        jPanelPacientesBotones = new javax.swing.JPanel();
        jButtonNuevo = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanelForm.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabel3.setText("Busqueda en Dieta por:");

        buttonGroup1.add(jRadioButtonDieta);
        jRadioButtonDieta.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 12)); // NOI18N
        jRadioButtonDieta.setSelected(true);
        jRadioButtonDieta.setLabel("Dieta");
        jRadioButtonDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDietaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonPaciente);
        jRadioButtonPaciente.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 12)); // NOI18N
        jRadioButtonPaciente.setText("Paciente");
        jRadioButtonPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDietaPacienteLayout = new javax.swing.GroupLayout(jPanelDietaPaciente);
        jPanelDietaPaciente.setLayout(jPanelDietaPacienteLayout);
        jPanelDietaPacienteLayout.setHorizontalGroup(
            jPanelDietaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDietaPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelDietaPacienteLayout.setVerticalGroup(
            jPanelDietaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDietaPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDietaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButtonDieta)
                    .addComponent(jRadioButtonPaciente))
                .addGap(5, 5, 5))
        );

        jPanelForm.add(jPanelDietaPaciente, java.awt.BorderLayout.NORTH);

        jPanelCardPacienteCard.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanelCardPacienteCardPropertyChange(evt);
            }
        });
        jPanelCardPacienteCard.setLayout(new java.awt.CardLayout());

        jLabelCodDieta.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelCodDieta.setText("Cod. Dieta:");
        jLabelCodDieta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldCodDieta.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jTextFieldCodDieta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldCodDieta.setMinimumSize(new java.awt.Dimension(14, 30));
        jTextFieldCodDieta.setPreferredSize(new java.awt.Dimension(200, 30));

        jPanelCond1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelCondSOps1Layout = new javax.swing.GroupLayout(jPanelCondSOps1);
        jPanelCondSOps1.setLayout(jPanelCondSOps1Layout);
        jPanelCondSOps1Layout.setHorizontalGroup(
            jPanelCondSOps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        jPanelCondSOps1Layout.setVerticalGroup(
            jPanelCondSOps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jPanelCond1.add(jPanelCondSOps1, "cardCondSOps2");

        jRadioButtonCondY1.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 12)); // NOI18N
        jRadioButtonCondY1.setText("Y");
        jRadioButtonCondY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCondY1ActionPerformed(evt);
            }
        });

        jRadioButtonCondO1.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 12)); // NOI18N
        jRadioButtonCondO1.setSelected(true);
        jRadioButtonCondO1.setText("O");
        jRadioButtonCondO1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCondO1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCondCOps1Layout = new javax.swing.GroupLayout(jPanelCondCOps1);
        jPanelCondCOps1.setLayout(jPanelCondCOps1Layout);
        jPanelCondCOps1Layout.setHorizontalGroup(
            jPanelCondCOps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCondCOps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCondY1)
                    .addComponent(jRadioButtonCondO1))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanelCondCOps1Layout.setVerticalGroup(
            jPanelCondCOps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jRadioButtonCondY1)
                .addGap(10, 10, 10)
                .addComponent(jRadioButtonCondO1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelCond1.add(jPanelCondCOps1, "cardCondCOps2");

        jLabelDietaNombre.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelDietaNombre.setText("Dieta Nombre:");
        jLabelDietaNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldDietaNombre.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jTextFieldDietaNombre.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabelEstadoDieta.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelEstadoDieta.setText("Estado de Dieta:");

        flatTriStateCheckBoxEstadoDieta.setText("Ambos");
        flatTriStateCheckBoxEstadoDieta.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 12)); // NOI18N
        flatTriStateCheckBoxEstadoDieta.setIndeterminate(false);

        jLabelRangoPesoRequerido.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelRangoPesoRequerido.setText("Peso Final en Rango:");

        flatTriStateCheckBoxRangoPesoRequerido.setText("Ambos");
        flatTriStateCheckBoxRangoPesoRequerido.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 12)); // NOI18N
        flatTriStateCheckBoxRangoPesoRequerido.setIndeterminate(false);

        jPanelCond2.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelCondSOps2Layout = new javax.swing.GroupLayout(jPanelCondSOps2);
        jPanelCondSOps2.setLayout(jPanelCondSOps2Layout);
        jPanelCondSOps2Layout.setHorizontalGroup(
            jPanelCondSOps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        jPanelCondSOps2Layout.setVerticalGroup(
            jPanelCondSOps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jPanelCond2.add(jPanelCondSOps2, "cardCondSOps2");

        jRadioButtonCondY2.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 12)); // NOI18N
        jRadioButtonCondY2.setText("Y");
        jRadioButtonCondY2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCondY2ActionPerformed(evt);
            }
        });

        jRadioButtonCondO2.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 12)); // NOI18N
        jRadioButtonCondO2.setSelected(true);
        jRadioButtonCondO2.setText("O");
        jRadioButtonCondO2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCondO2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCondCOps2Layout = new javax.swing.GroupLayout(jPanelCondCOps2);
        jPanelCondCOps2.setLayout(jPanelCondCOps2Layout);
        jPanelCondCOps2Layout.setHorizontalGroup(
            jPanelCondCOps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCondCOps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCondY2)
                    .addComponent(jRadioButtonCondO2))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanelCondCOps2Layout.setVerticalGroup(
            jPanelCondCOps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jRadioButtonCondY2)
                .addGap(10, 10, 10)
                .addComponent(jRadioButtonCondO2)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelCond2.add(jPanelCondCOps2, "cardCondCOps2");

        jPanelCond3.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelCondSOps3Layout = new javax.swing.GroupLayout(jPanelCondSOps3);
        jPanelCondSOps3.setLayout(jPanelCondSOps3Layout);
        jPanelCondSOps3Layout.setHorizontalGroup(
            jPanelCondSOps3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        jPanelCondSOps3Layout.setVerticalGroup(
            jPanelCondSOps3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jPanelCond3.add(jPanelCondSOps3, "cardCondSOps2");

        jRadioButtonCondY3.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 12)); // NOI18N
        jRadioButtonCondY3.setText("Y");
        jRadioButtonCondY3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCondY3ActionPerformed(evt);
            }
        });

        jRadioButtonCondO3.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 12)); // NOI18N
        jRadioButtonCondO3.setSelected(true);
        jRadioButtonCondO3.setText("O");
        jRadioButtonCondO3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCondO3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCondCOps3Layout = new javax.swing.GroupLayout(jPanelCondCOps3);
        jPanelCondCOps3.setLayout(jPanelCondCOps3Layout);
        jPanelCondCOps3Layout.setHorizontalGroup(
            jPanelCondCOps3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCondCOps3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCondY3)
                    .addComponent(jRadioButtonCondO3))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanelCondCOps3Layout.setVerticalGroup(
            jPanelCondCOps3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jRadioButtonCondY3)
                .addGap(10, 10, 10)
                .addComponent(jRadioButtonCondO3)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelCond3.add(jPanelCondCOps3, "cardCondCOps2");

        javax.swing.GroupLayout jPanelBusquedaDietaLayout = new javax.swing.GroupLayout(jPanelBusquedaDieta);
        jPanelBusquedaDieta.setLayout(jPanelBusquedaDietaLayout);
        jPanelBusquedaDietaLayout.setHorizontalGroup(
            jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaDietaLayout.createSequentialGroup()
                .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBusquedaDietaLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(filler9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelBusquedaDietaLayout.createSequentialGroup()
                                .addComponent(jLabelCodDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jTextFieldCodDieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(filler7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelBusquedaDietaLayout.createSequentialGroup()
                                .addComponent(jLabelEstadoDieta)
                                .addGap(18, 18, 18)
                                .addComponent(flatTriStateCheckBoxEstadoDieta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaDietaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(filler11, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelCond1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCond3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBusquedaDietaLayout.createSequentialGroup()
                        .addComponent(jLabelRangoPesoRequerido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flatTriStateCheckBoxRangoPesoRequerido, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBusquedaDietaLayout.createSequentialGroup()
                        .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelBusquedaDietaLayout.createSequentialGroup()
                                .addComponent(jLabelDietaNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldDietaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(filler8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filler10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addComponent(jPanelCond2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(filler13, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanelBusquedaDietaLayout.setVerticalGroup(
            jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaDietaLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBusquedaDietaLayout.createSequentialGroup()
                        .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBusquedaDietaLayout.createSequentialGroup()
                                .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filler7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(filler8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelCodDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldCodDieta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelBusquedaDietaLayout.createSequentialGroup()
                                        .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelDietaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldDietaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(filler10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanelCond2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBusquedaDietaLayout.createSequentialGroup()
                                .addComponent(filler9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelEstadoDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(flatTriStateCheckBoxEstadoDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBusquedaDietaLayout.createSequentialGroup()
                                    .addComponent(filler13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelRangoPesoRequerido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(flatTriStateCheckBoxRangoPesoRequerido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jPanelCond3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanelBusquedaDietaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(filler11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanelCond1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );

        jPanelCardPacienteCard.add(jPanelBusquedaDieta, "BusquedaDieta");

        jLabelDni.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelDni.setText("Documento:");
        jLabelDni.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldDni.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jTextFieldDni.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDni.setMinimumSize(new java.awt.Dimension(14, 30));
        jTextFieldDni.setPreferredSize(new java.awt.Dimension(200, 30));

        jPanelCond4.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelCondSOps4Layout = new javax.swing.GroupLayout(jPanelCondSOps4);
        jPanelCondSOps4.setLayout(jPanelCondSOps4Layout);
        jPanelCondSOps4Layout.setHorizontalGroup(
            jPanelCondSOps4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        jPanelCondSOps4Layout.setVerticalGroup(
            jPanelCondSOps4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jPanelCond4.add(jPanelCondSOps4, "cardCondSOps2");

        jRadioButtonCondY4.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 12)); // NOI18N
        jRadioButtonCondY4.setText("Y");
        jRadioButtonCondY4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCondY4ActionPerformed(evt);
            }
        });

        jRadioButtonCondO4.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 12)); // NOI18N
        jRadioButtonCondO4.setSelected(true);
        jRadioButtonCondO4.setText("O");
        jRadioButtonCondO4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCondO4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCondCOps4Layout = new javax.swing.GroupLayout(jPanelCondCOps4);
        jPanelCondCOps4.setLayout(jPanelCondCOps4Layout);
        jPanelCondCOps4Layout.setHorizontalGroup(
            jPanelCondCOps4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCondCOps4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCondY4)
                    .addComponent(jRadioButtonCondO4))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanelCondCOps4Layout.setVerticalGroup(
            jPanelCondCOps4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps4Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jRadioButtonCondY4)
                .addGap(10, 10, 10)
                .addComponent(jRadioButtonCondO4)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelCond4.add(jPanelCondCOps4, "cardCondCOps2");

        jLabelNombre.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombre:");
        jLabelNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldNombre.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabelEstado.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelEstado.setText("Estado:");

        flatTriStateCheckBoxEstado.setText("Ambos");
        flatTriStateCheckBoxEstado.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 12)); // NOI18N
        flatTriStateCheckBoxEstado.setIndeterminate(false);
        flatTriStateCheckBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flatTriStateCheckBoxEstadoActionPerformed(evt);
            }
        });

        jPanelCond5.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelCondSOps5Layout = new javax.swing.GroupLayout(jPanelCondSOps5);
        jPanelCondSOps5.setLayout(jPanelCondSOps5Layout);
        jPanelCondSOps5Layout.setHorizontalGroup(
            jPanelCondSOps5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        jPanelCondSOps5Layout.setVerticalGroup(
            jPanelCondSOps5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jPanelCond5.add(jPanelCondSOps5, "cardCondSOps2");

        jRadioButtonCondY5.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 12)); // NOI18N
        jRadioButtonCondY5.setText("Y");
        jRadioButtonCondY5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCondY5ActionPerformed(evt);
            }
        });

        jRadioButtonCondO5.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 12)); // NOI18N
        jRadioButtonCondO5.setSelected(true);
        jRadioButtonCondO5.setText("O");
        jRadioButtonCondO5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCondO5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCondCOps5Layout = new javax.swing.GroupLayout(jPanelCondCOps5);
        jPanelCondCOps5.setLayout(jPanelCondCOps5Layout);
        jPanelCondCOps5Layout.setHorizontalGroup(
            jPanelCondCOps5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCondCOps5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCondY5)
                    .addComponent(jRadioButtonCondO5))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanelCondCOps5Layout.setVerticalGroup(
            jPanelCondCOps5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps5Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jRadioButtonCondY5)
                .addGap(10, 10, 10)
                .addComponent(jRadioButtonCondO5)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelCond5.add(jPanelCondCOps5, "cardCondCOps2");

        jPanelCond6.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelCondSOps6Layout = new javax.swing.GroupLayout(jPanelCondSOps6);
        jPanelCondSOps6.setLayout(jPanelCondSOps6Layout);
        jPanelCondSOps6Layout.setHorizontalGroup(
            jPanelCondSOps6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        jPanelCondSOps6Layout.setVerticalGroup(
            jPanelCondSOps6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jPanelCond6.add(jPanelCondSOps6, "cardCondSOps2");

        jRadioButtonCondY6.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 12)); // NOI18N
        jRadioButtonCondY6.setText("Y");
        jRadioButtonCondY6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCondY6ActionPerformed(evt);
            }
        });

        jRadioButtonCondO6.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 12)); // NOI18N
        jRadioButtonCondO6.setSelected(true);
        jRadioButtonCondO6.setText("O");
        jRadioButtonCondO6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCondO6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCondCOps6Layout = new javax.swing.GroupLayout(jPanelCondCOps6);
        jPanelCondCOps6.setLayout(jPanelCondCOps6Layout);
        jPanelCondCOps6Layout.setHorizontalGroup(
            jPanelCondCOps6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCondCOps6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCondY6)
                    .addComponent(jRadioButtonCondO6))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanelCondCOps6Layout.setVerticalGroup(
            jPanelCondCOps6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps6Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jRadioButtonCondY6)
                .addGap(10, 10, 10)
                .addComponent(jRadioButtonCondO6)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelCond6.add(jPanelCondCOps6, "cardCondCOps2");

        jLabelApellido.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelApellido.setText("Apellido:");
        jLabelApellido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldApellido.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jTextFieldApellido.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldApellido.setMinimumSize(new java.awt.Dimension(14, 30));
        jTextFieldApellido.setPreferredSize(new java.awt.Dimension(200, 30));

        javax.swing.GroupLayout jPanelBusquedaPacienteLayout = new javax.swing.GroupLayout(jPanelBusquedaPaciente);
        jPanelBusquedaPaciente.setLayout(jPanelBusquedaPacienteLayout);
        jPanelBusquedaPacienteLayout.setHorizontalGroup(
            jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaPacienteLayout.createSequentialGroup()
                .addGroup(jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBusquedaPacienteLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(filler15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelBusquedaPacienteLayout.createSequentialGroup()
                                .addComponent(jLabelDni, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(filler12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filler17, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBusquedaPacienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelCond4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelCond6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBusquedaPacienteLayout.createSequentialGroup()
                        .addComponent(jLabelEstado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(flatTriStateCheckBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelBusquedaPacienteLayout.createSequentialGroup()
                        .addGroup(jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelBusquedaPacienteLayout.createSequentialGroup()
                                .addComponent(jLabelNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(filler14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(filler16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5)
                        .addComponent(jPanelCond5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(filler18, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanelBusquedaPacienteLayout.setVerticalGroup(
            jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBusquedaPacienteLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBusquedaPacienteLayout.createSequentialGroup()
                        .addGroup(jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBusquedaPacienteLayout.createSequentialGroup()
                                .addGroup(jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filler12, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(filler14, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0)
                                .addGroup(jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelBusquedaPacienteLayout.createSequentialGroup()
                                        .addGroup(jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelDni, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(filler17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelBusquedaPacienteLayout.createSequentialGroup()
                                        .addGroup(jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(filler16, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanelCond5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBusquedaPacienteLayout.createSequentialGroup()
                                .addComponent(filler15, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBusquedaPacienteLayout.createSequentialGroup()
                                    .addComponent(filler18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanelBusquedaPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(flatTriStateCheckBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jPanelCond6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanelCond4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5))
        );

        jPanelCardPacienteCard.add(jPanelBusquedaPaciente, "BusquedaPaciente");

        jPanelForm.add(jPanelCardPacienteCard, java.awt.BorderLayout.CENTER);

        add(jPanelForm, java.awt.BorderLayout.NORTH);

        jTreeDietas.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 12)); // NOI18N
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Dietas");
        jTreeDietas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTreeDietas);

        jPanelDetalles.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelDietaCenterLayout = new javax.swing.GroupLayout(jPanelDietaCenter);
        jPanelDietaCenter.setLayout(jPanelDietaCenterLayout);
        jPanelDietaCenterLayout.setHorizontalGroup(
            jPanelDietaCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDietaCenterLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDietaCenterLayout.setVerticalGroup(
            jPanelDietaCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDietaCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDietaCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                    .addComponent(jPanelDetalles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanelDietaCenter, java.awt.BorderLayout.CENTER);

        jButtonNuevo.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 14)); // NOI18N
        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.setMaximumSize(new java.awt.Dimension(200, 40));
        jButtonNuevo.setMinimumSize(new java.awt.Dimension(93, 30));
        jButtonNuevo.setPreferredSize(new java.awt.Dimension(93, 35));
        jButtonNuevo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonNuevoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonNuevoFocusLost(evt);
            }
        });
        jButtonNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonNuevoMouseExited(evt);
            }
        });
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 14)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setMaximumSize(new java.awt.Dimension(200, 40));
        jButtonSalir.setMinimumSize(new java.awt.Dimension(75, 30));
        jButtonSalir.setPreferredSize(new java.awt.Dimension(75, 35));
        jButtonSalir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonSalirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonSalirFocusLost(evt);
            }
        });
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseExited(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonBuscar.setBackground(new java.awt.Color(30, 30, 30));
        jButtonBuscar.setToolTipText("Buscar Por DNI");
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setContentAreaFilled(false);
        jButtonBuscar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonBuscar.setMaximumSize(new java.awt.Dimension(5000, 5000));
        jButtonBuscar.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonBuscar.setRequestFocusEnabled(false);
        jButtonBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonBuscarFocusLost(evt);
            }
        });
        jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonBuscarMousePressed(evt);
            }
        });
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jButtonBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButtonBuscarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanelPacientesBotonesLayout = new javax.swing.GroupLayout(jPanelPacientesBotones);
        jPanelPacientesBotones.setLayout(jPanelPacientesBotonesLayout);
        jPanelPacientesBotonesLayout.setHorizontalGroup(
            jPanelPacientesBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacientesBotonesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButtonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanelPacientesBotonesLayout.setVerticalGroup(
            jPanelPacientesBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacientesBotonesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelPacientesBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        add(jPanelPacientesBotones, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonCondY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCondY1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCondY1ActionPerformed

    private void jRadioButtonCondO1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCondO1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCondO1ActionPerformed

    private void jButtonBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonBuscarFocusGained
        controladorPacientesAdv.buttonBuscarFocusGained(evt);
    }//GEN-LAST:event_jButtonBuscarFocusGained

    private void jButtonBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonBuscarFocusLost
        controladorPacientesAdv.buttonBuscarFocusLost(evt);
    }//GEN-LAST:event_jButtonBuscarFocusLost

    private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseClicked
        controladorPacientesAdv.buttonBuscarMouseClicked(evt);
    }//GEN-LAST:event_jButtonBuscarMouseClicked

    private void jButtonBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseEntered
        controladorPacientesAdv.buttonBuscarMouseEntered(evt);
    }//GEN-LAST:event_jButtonBuscarMouseEntered

    private void jButtonBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseExited
        controladorPacientesAdv.buttonBuscarMouseExited(evt);
    }//GEN-LAST:event_jButtonBuscarMouseExited

    private void jButtonBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMousePressed
        controladorPacientesAdv.buttonBuscarMousePressed(evt);
    }//GEN-LAST:event_jButtonBuscarMousePressed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        controladorPacientesAdv.buscarPacienteActionPerformed(evt);
        
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonBuscarKeyReleased
        controladorPacientesAdv.buttonBuscarKeyReleased(evt);
    }//GEN-LAST:event_jButtonBuscarKeyReleased

    private void jButtonBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonBuscarKeyTyped
        controladorPacientesAdv.buttonBuscarKeyTyped(evt);
    }//GEN-LAST:event_jButtonBuscarKeyTyped

    private void jPanelCardPacienteCardPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanelCardPacienteCardPropertyChange
        System.out.println("BAZINGA");
    }//GEN-LAST:event_jPanelCardPacienteCardPropertyChange

    private void jButtonNuevoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonNuevoFocusGained
        controladorPacientesAdv.buttonNuevoFocusGained(evt);
    }//GEN-LAST:event_jButtonNuevoFocusGained

    private void jButtonNuevoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonNuevoFocusLost
        controladorPacientesAdv.buttonNuevoFocusLost(evt);
    }//GEN-LAST:event_jButtonNuevoFocusLost

    private void jButtonNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNuevoMouseEntered
        controladorPacientesAdv.buttonNuevoMouseEntered(evt);
    }//GEN-LAST:event_jButtonNuevoMouseEntered

    private void jButtonNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNuevoMouseExited
        controladorPacientesAdv.buttonNuevoMouseExited(evt);
    }//GEN-LAST:event_jButtonNuevoMouseExited

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        controladorPacientesAdv.nuevoPacienteActionPerformed(evt);
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonSalirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonSalirFocusGained
        controladorPacientesAdv.buttonSalirFocusGained(evt);
    }//GEN-LAST:event_jButtonSalirFocusGained

    private void jButtonSalirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonSalirFocusLost
        controladorPacientesAdv.buttonSalirFocusLost(evt);
    }//GEN-LAST:event_jButtonSalirFocusLost

    private void jButtonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseEntered
        controladorPacientesAdv.buttonSalirMouseEntered(evt);
    }//GEN-LAST:event_jButtonSalirMouseEntered

    private void jButtonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseExited
        controladorPacientesAdv.buttonSalirMouseExited(evt);
    }//GEN-LAST:event_jButtonSalirMouseExited

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        controladorPacientesAdv.salirPacienteActionPerformed(evt);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jRadioButtonCondY2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCondY2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCondY2ActionPerformed

    private void jRadioButtonCondO2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCondO2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCondO2ActionPerformed

    private void jRadioButtonCondY3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCondY3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCondY3ActionPerformed

    private void jRadioButtonCondO3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCondO3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCondO3ActionPerformed

    private void jRadioButtonCondY4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCondY4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCondY4ActionPerformed

    private void jRadioButtonCondO4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCondO4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCondO4ActionPerformed

    private void jRadioButtonCondY5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCondY5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCondY5ActionPerformed

    private void jRadioButtonCondO5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCondO5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCondO5ActionPerformed

    private void jRadioButtonCondY6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCondY6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCondY6ActionPerformed

    private void jRadioButtonCondO6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCondO6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCondO6ActionPerformed

    private void jRadioButtonDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDietaActionPerformed
        CardLayout cardLayout = (CardLayout) jPanelCardPacienteCard.getLayout();
        cardLayout.show(jPanelCardPacienteCard, "BusquedaDieta");
    }//GEN-LAST:event_jRadioButtonDietaActionPerformed

    private void jRadioButtonPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPacienteActionPerformed
        CardLayout cardLayout = (CardLayout) jPanelCardPacienteCard.getLayout();
        cardLayout.show(jPanelCardPacienteCard, "BusquedaPaciente");
        
    }//GEN-LAST:event_jRadioButtonPacienteActionPerformed

    private void flatTriStateCheckBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flatTriStateCheckBoxEstadoActionPerformed
        // TODO add your handling code here:
        System.out.println("isIndeterminate: "+flatTriStateCheckBoxEstado.isIndeterminate());
        System.out.println("isSelected: "+flatTriStateCheckBoxEstado.isSelected());
        String[] estados = {"Inactivo","Activo","Ambos"};
        triStateCheckBox(flatTriStateCheckBoxEstado, estados);
    }//GEN-LAST:event_flatTriStateCheckBoxEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.Box.Filler filler10;
    private javax.swing.Box.Filler filler11;
    private javax.swing.Box.Filler filler12;
    private javax.swing.Box.Filler filler13;
    private javax.swing.Box.Filler filler14;
    private javax.swing.Box.Filler filler15;
    private javax.swing.Box.Filler filler16;
    private javax.swing.Box.Filler filler17;
    private javax.swing.Box.Filler filler18;
    private javax.swing.Box.Filler filler7;
    private javax.swing.Box.Filler filler8;
    private javax.swing.Box.Filler filler9;
    private com.formdev.flatlaf.extras.components.FlatTriStateCheckBox flatTriStateCheckBoxEstado;
    private com.formdev.flatlaf.extras.components.FlatTriStateCheckBox flatTriStateCheckBoxEstadoDieta;
    private com.formdev.flatlaf.extras.components.FlatTriStateCheckBox flatTriStateCheckBoxRangoPesoRequerido;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCodDieta;
    private javax.swing.JLabel jLabelDietaNombre;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelEstadoDieta;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelRangoPesoRequerido;
    private javax.swing.JPanel jPanelBusquedaDieta;
    private javax.swing.JPanel jPanelBusquedaPaciente;
    private javax.swing.JPanel jPanelCardPacienteCard;
    private javax.swing.JPanel jPanelCond1;
    private javax.swing.JPanel jPanelCond2;
    private javax.swing.JPanel jPanelCond3;
    private javax.swing.JPanel jPanelCond4;
    private javax.swing.JPanel jPanelCond5;
    private javax.swing.JPanel jPanelCond6;
    private javax.swing.JPanel jPanelCondCOps1;
    private javax.swing.JPanel jPanelCondCOps2;
    private javax.swing.JPanel jPanelCondCOps3;
    private javax.swing.JPanel jPanelCondCOps4;
    private javax.swing.JPanel jPanelCondCOps5;
    private javax.swing.JPanel jPanelCondCOps6;
    private javax.swing.JPanel jPanelCondSOps1;
    private javax.swing.JPanel jPanelCondSOps2;
    private javax.swing.JPanel jPanelCondSOps3;
    private javax.swing.JPanel jPanelCondSOps4;
    private javax.swing.JPanel jPanelCondSOps5;
    private javax.swing.JPanel jPanelCondSOps6;
    private javax.swing.JPanel jPanelDetalles;
    private javax.swing.JPanel jPanelDietaCenter;
    private javax.swing.JPanel jPanelDietaPaciente;
    private javax.swing.JPanel jPanelForm;
    private javax.swing.JPanel jPanelPacientesBotones;
    private javax.swing.JRadioButton jRadioButtonCondO1;
    private javax.swing.JRadioButton jRadioButtonCondO2;
    private javax.swing.JRadioButton jRadioButtonCondO3;
    private javax.swing.JRadioButton jRadioButtonCondO4;
    private javax.swing.JRadioButton jRadioButtonCondO5;
    private javax.swing.JRadioButton jRadioButtonCondO6;
    private javax.swing.JRadioButton jRadioButtonCondY1;
    private javax.swing.JRadioButton jRadioButtonCondY2;
    private javax.swing.JRadioButton jRadioButtonCondY3;
    private javax.swing.JRadioButton jRadioButtonCondY4;
    private javax.swing.JRadioButton jRadioButtonCondY5;
    private javax.swing.JRadioButton jRadioButtonCondY6;
    private javax.swing.JRadioButton jRadioButtonDieta;
    private javax.swing.JRadioButton jRadioButtonPaciente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCodDieta;
    private javax.swing.JTextField jTextFieldDietaNombre;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTree jTreeDietas;
    // End of variables declaration//GEN-END:variables

    public DietaPanelMain getDietaPanelMain() {
        return dietaPanelMain;
    }

    public FlatTriStateCheckBox getFlatTriStateCheckBoxEstado() {
        return flatTriStateCheckBoxEstado;
    }

    public FlatTriStateCheckBox getFlatTriStateCheckBoxEstadoDieta() {
        return flatTriStateCheckBoxEstadoDieta;
    }

    public FlatTriStateCheckBox getFlatTriStateCheckBoxRangoPesoRequerido() {
        return flatTriStateCheckBoxRangoPesoRequerido;
    }

    public JButton getjButtonBuscar() {
        return jButtonBuscar;
    }

    public JButton getjButtonNuevo() {
        return jButtonNuevo;
    }

    public JButton getjButtonSalir() {
        return jButtonSalir;
    }

    public JLabel getjLabelApellido() {
        return jLabelApellido;
    }

    public JLabel getjLabelCodDieta() {
        return jLabelCodDieta;
    }

    public JLabel getjLabelDietaNombre() {
        return jLabelDietaNombre;
    }

    public JLabel getjLabelDni() {
        return jLabelDni;
    }

    public JLabel getjLabelNombre() {
        return jLabelNombre;
    }

    public JPanel getjPanelDetalles() {
        return jPanelDetalles;
    }

    public JTextField getjTextFieldApellido() {
        return jTextFieldApellido;
    }

    public JTextField getjTextFieldCodDieta() {
        return jTextFieldCodDieta;
    }

    public JTextField getjTextFieldDni() {
        return jTextFieldDni;
    }

    public JTextField getjTextFieldDietaNombre() {
        return jTextFieldDietaNombre;
    }

    public JTextField getjTextFieldNombre() {
        return jTextFieldNombre;
    }

    public JTree getjTreeDietas() {
        return jTreeDietas;
    }
    
    
}
