/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.awt.CardLayout;

/**
 *
 * @author Administrador
 */
public class PacientePanelMain extends javax.swing.JPanel {
    private PacientePanelMenu pacientePanelMenu;
    private PacientePanel pacientePanel;
    private PacientePanelAdv pacientePanelAdv;
    private CardLayout cardLayout;
    /**
     * Creates new form PacientePanelMain1
     */
    public PacientePanelMain() {
        initComponents();
        CrearPacientePaneles();
    }
    
    private void CrearPacientePaneles(){
        pacientePanelMenu = new PacientePanelMenu(this);
        pacientePanel = new PacientePanel(this);
        pacientePanelAdv = new PacientePanelAdv(this);
        add(pacientePanelMenu, "pacienteMenu");
        add(pacientePanel, "pacienteBas");
        add(pacientePanelAdv, "pacienteAdv");
        cardLayout = (CardLayout) getLayout();
        cardLayout.show(this, "pacienteMenu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 204, 102));
        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public PacientePanelMenu getPacientePanelMenu() {
        return pacientePanelMenu;
    }

    public PacientePanel getPacientePanel() {
        return pacientePanel;
    }

    public PacientePanelAdv getPacientePanelAdv() {
        return pacientePanelAdv;
    }

    public CardLayout getCardLayout() {
        return cardLayout;
    }
    
}
