/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.ControladorPacientesAdv;
import Vistas.Render.RenderTable;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Administrador
 */
public class PacientePanelAdv extends java.awt.Panel {

    private final PacientePanelMain pacientePanelMain;
    private final ControladorPacientesAdv controladorPacientesAdv;
    private DefaultTableModel tableModel = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };

    /**
     * Creates new form PacientePanelAdv
     * @param pacientePanelMain
     */
    public PacientePanelAdv(PacientePanelMain pacientePanelMain) {
        initComponents();
        setTableModel();
        this.pacientePanelMain = pacientePanelMain;
        controladorPacientesAdv = new ControladorPacientesAdv(this);
        jButtonBuscar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButtonLimpiarForm.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButtonNuevo.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButtonSalir.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jButtonVolver.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }

    private void setTableModel() {
        DefaultTableCellRenderer alinearCentro = new DefaultTableCellRenderer();
        DefaultTableCellRenderer alinearDerecha = new DefaultTableCellRenderer();
        alinearCentro.setHorizontalAlignment(JLabel.CENTER);
        alinearDerecha.setHorizontalAlignment(JLabel.RIGHT);
        String[] cabecera = {"ID", "Documento", "Apellido", "Nombre", "Fecha de Nac.", "Estado", "Editar", "Dietas"};
        tableModel.setColumnIdentifiers(cabecera);
        jTablePacientes.setDefaultRenderer(Object.class, new RenderTable());
        jTablePacientes.setModel(tableModel);

        JTableHeader propiedadesCabecera = jTablePacientes.getTableHeader();
        propiedadesCabecera.setFont(new Font("JetBrains Mono NL Thin", Font.PLAIN, 14));
        propiedadesCabecera.setBackground(new Color(72, 101, 156));

        jTablePacientes.getTableHeader().getColumnModel().getColumn(0).setPreferredWidth(50);
        jTablePacientes.getTableHeader().getColumnModel().getColumn(1).setPreferredWidth(100);
        jTablePacientes.getTableHeader().getColumnModel().getColumn(2).setPreferredWidth(200);
        jTablePacientes.getTableHeader().getColumnModel().getColumn(3).setPreferredWidth(200);
        jTablePacientes.getTableHeader().getColumnModel().getColumn(4).setPreferredWidth(100);
        jTablePacientes.getTableHeader().getColumnModel().getColumn(5).setPreferredWidth(75);
        jTablePacientes.getTableHeader().getColumnModel().getColumn(6).setPreferredWidth(30);
        jTablePacientes.getTableHeader().getColumnModel().getColumn(7).setPreferredWidth(30);

        jTablePacientes.getColumnModel().getColumn(0).setCellRenderer(alinearCentro);
        jTablePacientes.getColumnModel().getColumn(1).setCellRenderer(alinearDerecha);
        jTablePacientes.getColumnModel().getColumn(4).setCellRenderer(alinearCentro);
        jTablePacientes.getColumnModel().getColumn(5).setCellRenderer(alinearCentro);
        jTablePacientes.getColumnModel().getColumn(6).setCellRenderer(alinearCentro);
        jTablePacientes.getColumnModel().getColumn(7).setCellRenderer(alinearCentro);

        jTablePacientes.setShowGrid(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanelPacientes = new javax.swing.JPanel();
        jPanelPacienteForm = new javax.swing.JPanel();
        jPanelDniApellidoNombre = new javax.swing.JPanel();
        jLabelDni = new javax.swing.JLabel();
        jTextFieldDni = new javax.swing.JTextField();
        jPanelCond1 = new javax.swing.JPanel();
        jPanelCondSOps1 = new javax.swing.JPanel();
        jPanelCondCOps1 = new javax.swing.JPanel();
        jRadioButtonCondY1 = new javax.swing.JRadioButton();
        jRadioButtonCondO1 = new javax.swing.JRadioButton();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldApellido = new javax.swing.JTextField();
        jPanelCond2 = new javax.swing.JPanel();
        jPanelCondSOps2 = new javax.swing.JPanel();
        jPanelCondCOps2 = new javax.swing.JPanel();
        jRadioButtonCondY2 = new javax.swing.JRadioButton();
        jRadioButtonCondO2 = new javax.swing.JRadioButton();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelSearchCond = new javax.swing.JLabel();
        jCheckBoxCond = new javax.swing.JCheckBox();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10), new java.awt.Dimension(10, 10));
        jPanelFechaNac = new javax.swing.JPanel();
        jLabelFechaNacTitulo = new javax.swing.JLabel();
        jCheckBoxrangoFechaNac = new javax.swing.JCheckBox();
        jPanelCond3 = new javax.swing.JPanel();
        jPanelCondSOps3 = new javax.swing.JPanel();
        jPanelCondCOps3 = new javax.swing.JPanel();
        jRadioButtonCondY3 = new javax.swing.JRadioButton();
        jRadioButtonCondO3 = new javax.swing.JRadioButton();
        jPanelCardFechaNac = new javax.swing.JPanel();
        jPanelFechaNacSRango = new javax.swing.JPanel();
        jPanelSRango = new javax.swing.JPanel();
        jLabelFechaNac = new javax.swing.JLabel();
        jDateChooserFNac = new com.toedter.calendar.JDateChooser();
        jPanelFechaNacCRango = new javax.swing.JPanel();
        jPanelCRango = new javax.swing.JPanel();
        jLabelFechaNacDesde = new javax.swing.JLabel();
        jDateChooserFNacDesde = new com.toedter.calendar.JDateChooser();
        jLabelFechaNacHasta = new javax.swing.JLabel();
        jDateChooserFNacHasta = new com.toedter.calendar.JDateChooser();
        jPanelPacientesTabla = new javax.swing.JPanel();
        jPanelTabla = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePacientes = new javax.swing.JTable();
        jPanelPacientesBotones = new javax.swing.JPanel();
        jButtonNuevo = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jButtonLimpiarForm = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanelPacienteForm.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanelPacienteFormPropertyChange(evt);
            }
        });

        jLabelDni.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelDni.setText("Documento:");
        jLabelDni.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldDni.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jTextFieldDni.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDni.setMinimumSize(new java.awt.Dimension(14, 30));
        jTextFieldDni.setPreferredSize(new java.awt.Dimension(200, 30));

        jPanelCond1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelCondSOps1Layout = new javax.swing.GroupLayout(jPanelCondSOps1);
        jPanelCondSOps1.setLayout(jPanelCondSOps1Layout);
        jPanelCondSOps1Layout.setHorizontalGroup(
            jPanelCondSOps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        jPanelCondSOps1Layout.setVerticalGroup(
            jPanelCondSOps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jPanelCond1.add(jPanelCondSOps1, "cardCondSOps1");

        buttonGroup1.add(jRadioButtonCondY1);
        jRadioButtonCondY1.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 12)); // NOI18N
        jRadioButtonCondY1.setText("Y");

        buttonGroup1.add(jRadioButtonCondO1);
        jRadioButtonCondO1.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 12)); // NOI18N
        jRadioButtonCondO1.setSelected(true);
        jRadioButtonCondO1.setText("O");

        javax.swing.GroupLayout jPanelCondCOps1Layout = new javax.swing.GroupLayout(jPanelCondCOps1);
        jPanelCondCOps1.setLayout(jPanelCondCOps1Layout);
        jPanelCondCOps1Layout.setHorizontalGroup(
            jPanelCondCOps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCondCOps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCondY1)
                    .addComponent(jRadioButtonCondO1))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanelCondCOps1Layout.setVerticalGroup(
            jPanelCondCOps1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jRadioButtonCondY1)
                .addGap(10, 10, 10)
                .addComponent(jRadioButtonCondO1)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelCond1.add(jPanelCondCOps1, "cardCondCOps1");

        jLabelApellido.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelApellido.setText("Apellido:");
        jLabelApellido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldApellido.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jTextFieldApellido.setPreferredSize(new java.awt.Dimension(200, 30));

        jPanelCond2.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelCondSOps2Layout = new javax.swing.GroupLayout(jPanelCondSOps2);
        jPanelCondSOps2.setLayout(jPanelCondSOps2Layout);
        jPanelCondSOps2Layout.setHorizontalGroup(
            jPanelCondSOps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );
        jPanelCondSOps2Layout.setVerticalGroup(
            jPanelCondSOps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 85, Short.MAX_VALUE)
        );

        jPanelCond2.add(jPanelCondSOps2, "cardCondSOps2");

        buttonGroup2.add(jRadioButtonCondY2);
        jRadioButtonCondY2.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 12)); // NOI18N
        jRadioButtonCondY2.setText("Y");

        buttonGroup2.add(jRadioButtonCondO2);
        jRadioButtonCondO2.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 12)); // NOI18N
        jRadioButtonCondO2.setSelected(true);
        jRadioButtonCondO2.setText("O");

        javax.swing.GroupLayout jPanelCondCOps2Layout = new javax.swing.GroupLayout(jPanelCondCOps2);
        jPanelCondCOps2.setLayout(jPanelCondCOps2Layout);
        jPanelCondCOps2Layout.setHorizontalGroup(
            jPanelCondCOps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelCondCOps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCondY2)
                    .addComponent(jRadioButtonCondO2))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanelCondCOps2Layout.setVerticalGroup(
            jPanelCondCOps2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jRadioButtonCondY2)
                .addGap(10, 10, 10)
                .addComponent(jRadioButtonCondO2)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelCond2.add(jPanelCondCOps2, "cardCondCOps2");

        jLabelNombre.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombre:");
        jLabelNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTextFieldNombre.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabelSearchCond.setFont(new java.awt.Font("JetBrains Mono NL Thin", 1, 18)); // NOI18N
        jLabelSearchCond.setText("Bunqueda Por Condición:");
        jLabelSearchCond.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jCheckBoxCond.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxCondItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanelDniApellidoNombreLayout = new javax.swing.GroupLayout(jPanelDniApellidoNombre);
        jPanelDniApellidoNombre.setLayout(jPanelDniApellidoNombreLayout);
        jPanelDniApellidoNombreLayout.setHorizontalGroup(
            jPanelDniApellidoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDniApellidoNombreLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelDniApellidoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDniApellidoNombreLayout.createSequentialGroup()
                        .addComponent(jLabelSearchCond)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBoxCond, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelDni, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDniApellidoNombreLayout.createSequentialGroup()
                        .addComponent(jPanelCond1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDniApellidoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDniApellidoNombreLayout.createSequentialGroup()
                                .addGap(437, 437, 437)
                                .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDniApellidoNombreLayout.createSequentialGroup()
                                .addGroup(jPanelDniApellidoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filler3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelDniApellidoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanelDniApellidoNombreLayout.createSequentialGroup()
                                            .addComponent(jLabelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanelCond2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addGroup(jPanelDniApellidoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(filler6, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(50, 50, 50))
        );
        jPanelDniApellidoNombreLayout.setVerticalGroup(
            jPanelDniApellidoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDniApellidoNombreLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelDniApellidoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDniApellidoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelDni, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelDniApellidoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jCheckBoxCond, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSearchCond, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelDniApellidoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDniApellidoNombreLayout.createSequentialGroup()
                        .addComponent(filler5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDniApellidoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelCond2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDniApellidoNombreLayout.createSequentialGroup()
                        .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDniApellidoNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelCond1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelFechaNacTitulo.setFont(new java.awt.Font("JetBrains Mono NL Thin", 1, 18)); // NOI18N
        jLabelFechaNacTitulo.setText("Fecha de Nacimiento:");
        jLabelFechaNacTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelFechaNacTitulo.setPreferredSize(new java.awt.Dimension(300, 25));

        jCheckBoxrangoFechaNac.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 12)); // NOI18N
        jCheckBoxrangoFechaNac.setText("(Busqueda por Rango de Fecha)");
        jCheckBoxrangoFechaNac.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBoxrangoFechaNacItemStateChanged(evt);
            }
        });

        jPanelCond3.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelCondSOps3Layout = new javax.swing.GroupLayout(jPanelCondSOps3);
        jPanelCondSOps3.setLayout(jPanelCondSOps3Layout);
        jPanelCondSOps3Layout.setHorizontalGroup(
            jPanelCondSOps3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );
        jPanelCondSOps3Layout.setVerticalGroup(
            jPanelCondSOps3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        jPanelCond3.add(jPanelCondSOps3, "cardCondSOps3");

        buttonGroup3.add(jRadioButtonCondY3);
        jRadioButtonCondY3.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 12)); // NOI18N
        jRadioButtonCondY3.setText("Y");

        buttonGroup3.add(jRadioButtonCondO3);
        jRadioButtonCondO3.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 12)); // NOI18N
        jRadioButtonCondO3.setSelected(true);
        jRadioButtonCondO3.setText("O");

        javax.swing.GroupLayout jPanelCondCOps3Layout = new javax.swing.GroupLayout(jPanelCondCOps3);
        jPanelCondCOps3.setLayout(jPanelCondCOps3Layout);
        jPanelCondCOps3Layout.setHorizontalGroup(
            jPanelCondCOps3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCondCOps3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonCondY3)
                    .addComponent(jRadioButtonCondO3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCondCOps3Layout.setVerticalGroup(
            jPanelCondCOps3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCondCOps3Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jRadioButtonCondY3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonCondO3)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanelCond3.add(jPanelCondCOps3, "cardCondCOps3");

        jPanelCardFechaNac.setLayout(new java.awt.CardLayout(5, 5));

        jLabelFechaNac.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelFechaNac.setText("Fecha:");
        jLabelFechaNac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelFechaNac.setPreferredSize(new java.awt.Dimension(300, 25));

        jDateChooserFNac.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jDateChooserFNac.setPreferredSize(new java.awt.Dimension(118, 30));

        javax.swing.GroupLayout jPanelSRangoLayout = new javax.swing.GroupLayout(jPanelSRango);
        jPanelSRango.setLayout(jPanelSRangoLayout);
        jPanelSRangoLayout.setHorizontalGroup(
            jPanelSRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSRangoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jDateChooserFNac, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(456, Short.MAX_VALUE))
        );
        jPanelSRangoLayout.setVerticalGroup(
            jPanelSRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSRangoLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanelSRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserFNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFechaNacSRangoLayout = new javax.swing.GroupLayout(jPanelFechaNacSRango);
        jPanelFechaNacSRango.setLayout(jPanelFechaNacSRangoLayout);
        jPanelFechaNacSRangoLayout.setHorizontalGroup(
            jPanelFechaNacSRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFechaNacSRangoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSRango, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelFechaNacSRangoLayout.setVerticalGroup(
            jPanelFechaNacSRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFechaNacSRangoLayout.createSequentialGroup()
                .addComponent(jPanelSRango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelCardFechaNac.add(jPanelFechaNacSRango, "cardSRango");

        jLabelFechaNacDesde.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelFechaNacDesde.setText("Desde:");
        jLabelFechaNacDesde.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelFechaNacDesde.setPreferredSize(new java.awt.Dimension(300, 25));

        jDateChooserFNacDesde.setFont(new java.awt.Font("JetBrains Mono NL Thin", 1, 18)); // NOI18N
        jDateChooserFNacDesde.setPreferredSize(new java.awt.Dimension(118, 30));

        jLabelFechaNacHasta.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 18)); // NOI18N
        jLabelFechaNacHasta.setText("Hasta:");
        jLabelFechaNacHasta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelFechaNacHasta.setPreferredSize(new java.awt.Dimension(300, 25));

        jDateChooserFNacHasta.setFont(new java.awt.Font("JetBrains Mono NL Thin", 1, 18)); // NOI18N
        jDateChooserFNacHasta.setPreferredSize(new java.awt.Dimension(118, 30));

        javax.swing.GroupLayout jPanelCRangoLayout = new javax.swing.GroupLayout(jPanelCRango);
        jPanelCRango.setLayout(jPanelCRangoLayout);
        jPanelCRangoLayout.setHorizontalGroup(
            jPanelCRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCRangoLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabelFechaNacDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDateChooserFNacDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jLabelFechaNacHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jDateChooserFNacHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanelCRangoLayout.setVerticalGroup(
            jPanelCRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCRangoLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanelCRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelFechaNacHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserFNacHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelFechaNacDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserFNacDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFechaNacCRangoLayout = new javax.swing.GroupLayout(jPanelFechaNacCRango);
        jPanelFechaNacCRango.setLayout(jPanelFechaNacCRangoLayout);
        jPanelFechaNacCRangoLayout.setHorizontalGroup(
            jPanelFechaNacCRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 779, Short.MAX_VALUE)
            .addGroup(jPanelFechaNacCRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFechaNacCRangoLayout.createSequentialGroup()
                    .addComponent(jPanelCRango, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelFechaNacCRangoLayout.setVerticalGroup(
            jPanelFechaNacCRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
            .addGroup(jPanelFechaNacCRangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelFechaNacCRangoLayout.createSequentialGroup()
                    .addComponent(jPanelCRango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanelCardFechaNac.add(jPanelFechaNacCRango, "cardCRango");

        javax.swing.GroupLayout jPanelFechaNacLayout = new javax.swing.GroupLayout(jPanelFechaNac);
        jPanelFechaNac.setLayout(jPanelFechaNacLayout);
        jPanelFechaNacLayout.setHorizontalGroup(
            jPanelFechaNacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFechaNacLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanelFechaNacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFechaNacLayout.createSequentialGroup()
                        .addComponent(jPanelCond3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCardFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelFechaNacLayout.createSequentialGroup()
                        .addComponent(jLabelFechaNacTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jCheckBoxrangoFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelFechaNacLayout.setVerticalGroup(
            jPanelFechaNacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFechaNacLayout.createSequentialGroup()
                .addGroup(jPanelFechaNacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFechaNacTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxrangoFechaNac))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanelFechaNacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCond3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCardFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPacienteFormLayout = new javax.swing.GroupLayout(jPanelPacienteForm);
        jPanelPacienteForm.setLayout(jPanelPacienteFormLayout);
        jPanelPacienteFormLayout.setHorizontalGroup(
            jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacienteFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelPacienteFormLayout.createSequentialGroup()
                        .addComponent(jPanelDniApellidoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelPacienteFormLayout.setVerticalGroup(
            jPanelPacienteFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPacienteFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDniApellidoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTablePacientes.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 14)); // NOI18N
        jTablePacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DNI", "Apellido", "Nombre", "Fecha de Nac.", "Estado", "Editar", "Dietas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTablePacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacientesMouseClicked(evt);
            }
        });
        jTablePacientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTablePacientesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePacientes);

        javax.swing.GroupLayout jPanelTablaLayout = new javax.swing.GroupLayout(jPanelTabla);
        jPanelTabla.setLayout(jPanelTablaLayout);
        jPanelTablaLayout.setHorizontalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTablaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanelTablaLayout.setVerticalGroup(
            jPanelTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTablaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout jPanelPacientesTablaLayout = new javax.swing.GroupLayout(jPanelPacientesTabla);
        jPanelPacientesTabla.setLayout(jPanelPacientesTablaLayout);
        jPanelPacientesTablaLayout.setHorizontalGroup(
            jPanelPacientesTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPacientesTablaLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanelPacientesTablaLayout.setVerticalGroup(
            jPanelPacientesTablaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPacientesTablaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPacientesLayout = new javax.swing.GroupLayout(jPanelPacientes);
        jPanelPacientes.setLayout(jPanelPacientesLayout);
        jPanelPacientesLayout.setHorizontalGroup(
            jPanelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacientesLayout.createSequentialGroup()
                .addGroup(jPanelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelPacienteForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPacientesTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelPacientesLayout.setVerticalGroup(
            jPanelPacientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPacientesLayout.createSequentialGroup()
                .addComponent(jPanelPacienteForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelPacientesTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanelPacientes, java.awt.BorderLayout.CENTER);

        jButtonNuevo.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 14)); // NOI18N
        jButtonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AddUserMale48px.png"))); // NOI18N
        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.setToolTipText("Nuevo Paciente");
        jButtonNuevo.setMaximumSize(new java.awt.Dimension(200, 40));
        jButtonNuevo.setMinimumSize(new java.awt.Dimension(93, 30));
        jButtonNuevo.setPreferredSize(new java.awt.Dimension(93, 35));
        jButtonNuevo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonNuevoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonNuevoFocusLost(evt);
            }
        });
        jButtonNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonNuevoMouseExited(evt);
            }
        });
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("JetBrains Mono NL Thin", 0, 14)); // NOI18N
        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CloseWindow.png"))); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setToolTipText("Salir del Programa");
        jButtonSalir.setMaximumSize(new java.awt.Dimension(200, 40));
        jButtonSalir.setMinimumSize(new java.awt.Dimension(75, 30));
        jButtonSalir.setPreferredSize(new java.awt.Dimension(75, 35));
        jButtonSalir.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonSalirFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonSalirFocusLost(evt);
            }
        });
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseExited(evt);
            }
        });
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonBuscar.setBackground(new java.awt.Color(30, 30, 30));
        jButtonBuscar.setFont(new java.awt.Font("JetBrains Mono NL Thin", 1, 12)); // NOI18N
        jButtonBuscar.setToolTipText("Buscar");
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setContentAreaFilled(false);
        jButtonBuscar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonBuscar.setMaximumSize(new java.awt.Dimension(5000, 5000));
        jButtonBuscar.setPreferredSize(new java.awt.Dimension(40, 40));
        jButtonBuscar.setRequestFocusEnabled(false);
        jButtonBuscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonBuscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonBuscarFocusLost(evt);
            }
        });
        jButtonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonBuscarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonBuscarMousePressed(evt);
            }
        });
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        jButtonBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButtonBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButtonBuscarKeyTyped(evt);
            }
        });

        jButtonVolver.setBackground(new java.awt.Color(30, 30, 30));
        jButtonVolver.setFont(new java.awt.Font("JetBrains Mono Thin", 1, 12)); // NOI18N
        jButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BackArrow48px.png"))); // NOI18N
        jButtonVolver.setToolTipText("Volver");
        jButtonVolver.setBorder(null);
        jButtonVolver.setContentAreaFilled(false);
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonLimpiarForm.setBackground(new java.awt.Color(30, 30, 30));
        jButtonLimpiarForm.setFont(new java.awt.Font("JetBrains Mono NL Thin", 1, 12)); // NOI18N
        jButtonLimpiarForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Broom48px.png"))); // NOI18N
        jButtonLimpiarForm.setToolTipText("Limpiar");
        jButtonLimpiarForm.setBorder(null);
        jButtonLimpiarForm.setContentAreaFilled(false);
        jButtonLimpiarForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPacientesBotonesLayout = new javax.swing.GroupLayout(jPanelPacientesBotones);
        jPanelPacientesBotones.setLayout(jPanelPacientesBotonesLayout);
        jPanelPacientesBotonesLayout.setHorizontalGroup(
            jPanelPacientesBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacientesBotonesLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButtonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jButtonLimpiarForm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanelPacientesBotonesLayout.setVerticalGroup(
            jPanelPacientesBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPacientesBotonesLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanelPacientesBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonLimpiarForm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPacientesBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(jPanelPacientesBotones, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxCondItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxCondItemStateChanged
        controladorPacientesAdv.checkBoxCondItemStateChanged(evt);
    }//GEN-LAST:event_jCheckBoxCondItemStateChanged

    private void jCheckBoxrangoFechaNacItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBoxrangoFechaNacItemStateChanged
        controladorPacientesAdv.checkBoxrangoFechaNacItemStateChanged(evt);
    }//GEN-LAST:event_jCheckBoxrangoFechaNacItemStateChanged

    private void jButtonBuscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonBuscarFocusGained
        controladorPacientesAdv.buttonBuscarFocusGained(evt);
    }//GEN-LAST:event_jButtonBuscarFocusGained

    private void jButtonBuscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonBuscarFocusLost
        controladorPacientesAdv.buttonBuscarFocusLost(evt);
    }//GEN-LAST:event_jButtonBuscarFocusLost

    private void jButtonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseClicked
        controladorPacientesAdv.buttonBuscarMouseClicked(evt);
    }//GEN-LAST:event_jButtonBuscarMouseClicked

    private void jButtonBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseEntered
        controladorPacientesAdv.buttonBuscarMouseEntered(evt);
    }//GEN-LAST:event_jButtonBuscarMouseEntered

    private void jButtonBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMouseExited
        controladorPacientesAdv.buttonBuscarMouseExited(evt);
    }//GEN-LAST:event_jButtonBuscarMouseExited

    private void jButtonBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarMousePressed
        controladorPacientesAdv.buttonBuscarMousePressed(evt);
    }//GEN-LAST:event_jButtonBuscarMousePressed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        controladorPacientesAdv.buscarPacienteActionPerformed(evt);
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonBuscarKeyReleased
        controladorPacientesAdv.buttonBuscarKeyReleased(evt);
    }//GEN-LAST:event_jButtonBuscarKeyReleased

    private void jButtonBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonBuscarKeyTyped
        controladorPacientesAdv.buttonBuscarKeyTyped(evt);
    }//GEN-LAST:event_jButtonBuscarKeyTyped

    private void jPanelPacienteFormPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanelPacienteFormPropertyChange
        System.out.println("BAZINGA");
    }//GEN-LAST:event_jPanelPacienteFormPropertyChange

    private void jTablePacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacientesMouseClicked
        controladorPacientesAdv.tablePacientesMouseClicked(evt);
    }//GEN-LAST:event_jTablePacientesMouseClicked

    private void jTablePacientesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTablePacientesKeyReleased
        controladorPacientesAdv.tablePacientesKeyReleased(evt);
    }//GEN-LAST:event_jTablePacientesKeyReleased

    private void jButtonNuevoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonNuevoFocusGained
        controladorPacientesAdv.buttonNuevoFocusGained(evt);
    }//GEN-LAST:event_jButtonNuevoFocusGained

    private void jButtonNuevoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonNuevoFocusLost
        controladorPacientesAdv.buttonNuevoFocusLost(evt);
    }//GEN-LAST:event_jButtonNuevoFocusLost

    private void jButtonNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNuevoMouseEntered
        controladorPacientesAdv.buttonNuevoMouseEntered(evt);
    }//GEN-LAST:event_jButtonNuevoMouseEntered

    private void jButtonNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNuevoMouseExited
        controladorPacientesAdv.buttonNuevoMouseExited(evt);
    }//GEN-LAST:event_jButtonNuevoMouseExited

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        controladorPacientesAdv.nuevoPacienteActionPerformed(evt);
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonSalirFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonSalirFocusGained
        controladorPacientesAdv.buttonSalirFocusGained(evt);
    }//GEN-LAST:event_jButtonSalirFocusGained

    private void jButtonSalirFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonSalirFocusLost
        controladorPacientesAdv.buttonSalirFocusLost(evt);
    }//GEN-LAST:event_jButtonSalirFocusLost

    private void jButtonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseEntered
        controladorPacientesAdv.buttonSalirMouseEntered(evt);
    }//GEN-LAST:event_jButtonSalirMouseEntered

    private void jButtonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseExited
        controladorPacientesAdv.buttonSalirMouseExited(evt);
    }//GEN-LAST:event_jButtonSalirMouseExited

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        controladorPacientesAdv.salirPacienteActionPerformed(evt);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        controladorPacientesAdv.buttonVolverActionPerformed(evt);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonLimpiarFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarFormActionPerformed
        controladorPacientesAdv.buttonLimpiarFormActionPerformed(evt);
    }//GEN-LAST:event_jButtonLimpiarFormActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonLimpiarForm;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JCheckBox jCheckBoxCond;
    private javax.swing.JCheckBox jCheckBoxrangoFechaNac;
    private com.toedter.calendar.JDateChooser jDateChooserFNac;
    private com.toedter.calendar.JDateChooser jDateChooserFNacDesde;
    private com.toedter.calendar.JDateChooser jDateChooserFNacHasta;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelDni;
    private javax.swing.JLabel jLabelFechaNac;
    private javax.swing.JLabel jLabelFechaNacDesde;
    private javax.swing.JLabel jLabelFechaNacHasta;
    private javax.swing.JLabel jLabelFechaNacTitulo;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelSearchCond;
    private javax.swing.JPanel jPanelCRango;
    private javax.swing.JPanel jPanelCardFechaNac;
    private javax.swing.JPanel jPanelCond1;
    private javax.swing.JPanel jPanelCond2;
    private javax.swing.JPanel jPanelCond3;
    private javax.swing.JPanel jPanelCondCOps1;
    private javax.swing.JPanel jPanelCondCOps2;
    private javax.swing.JPanel jPanelCondCOps3;
    private javax.swing.JPanel jPanelCondSOps1;
    private javax.swing.JPanel jPanelCondSOps2;
    private javax.swing.JPanel jPanelCondSOps3;
    private javax.swing.JPanel jPanelDniApellidoNombre;
    private javax.swing.JPanel jPanelFechaNac;
    private javax.swing.JPanel jPanelFechaNacCRango;
    private javax.swing.JPanel jPanelFechaNacSRango;
    private javax.swing.JPanel jPanelPacienteForm;
    private javax.swing.JPanel jPanelPacientes;
    private javax.swing.JPanel jPanelPacientesBotones;
    private javax.swing.JPanel jPanelPacientesTabla;
    private javax.swing.JPanel jPanelSRango;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JRadioButton jRadioButtonCondO1;
    private javax.swing.JRadioButton jRadioButtonCondO2;
    private javax.swing.JRadioButton jRadioButtonCondO3;
    private javax.swing.JRadioButton jRadioButtonCondY1;
    private javax.swing.JRadioButton jRadioButtonCondY2;
    private javax.swing.JRadioButton jRadioButtonCondY3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePacientes;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

    public DefaultTableModel getTableModel() {
        return tableModel;
    }

    public JButton getjButtonNuevo() {
        return jButtonNuevo;
    }

    public JButton getjButtonLimpiarForm() {
        return jButtonLimpiarForm;
    }

    public JButton getjButtonVolver() {
        return jButtonVolver;
    }

    public JButton getjButtonBuscar() {
        return jButtonBuscar;
    }

    public JButton getjButtonSalir() {
        return jButtonSalir;
    }

    public JCheckBox getjCheckBoxCond() {
        return jCheckBoxCond;
    }

    public JCheckBox getjCheckBoxrangoFechaNac() {
        return jCheckBoxrangoFechaNac;
    }

    public JDateChooser getjDateChooserFNac() {
        return jDateChooserFNac;
    }

    public JDateChooser getjDateChooserFNacDesde() {
        return jDateChooserFNacDesde;
    }

    public JDateChooser getjDateChooserFNacHasta() {
        return jDateChooserFNacHasta;
    }

    public JLabel getjLabelApellido() {
        return jLabelApellido;
    }

    public JLabel getjLabelDni() {
        return jLabelDni;
    }

    public JLabel getjLabelFechaNac() {
        return jLabelFechaNac;
    }

    public JLabel getjLabelFechaNacDesde() {
        return jLabelFechaNacDesde;
    }

    public JLabel getjLabelFechaNacHasta() {
        return jLabelFechaNacHasta;
    }

    public JLabel getjLabelFechaNacTitulo() {
        return jLabelFechaNacTitulo;
    }

    public JLabel getjLabelNombre() {
        return jLabelNombre;
    }

    public JRadioButton getjRadioButtonCondO1() {
        return jRadioButtonCondO1;
    }

    public JRadioButton getjRadioButtonCondO2() {
        return jRadioButtonCondO2;
    }

    public JRadioButton getjRadioButtonCondO3() {
        return jRadioButtonCondO3;
    }

    public JRadioButton getjRadioButtonCondY1() {
        return jRadioButtonCondY1;
    }

    public JRadioButton getjRadioButtonCondY2() {
        return jRadioButtonCondY2;
    }

    public JRadioButton getjRadioButtonCondY3() {
        return jRadioButtonCondY3;
    }

    public JTable getjTablePacientes() {
        return jTablePacientes;
    }

    public JTextField getjTextFieldApellido() {
        return jTextFieldApellido;
    }

    public JTextField getjTextFieldDni() {
        return jTextFieldDni;
    }

    public JTextField getjTextFieldNombre() {
        return jTextFieldNombre;
    }

    public JPanel getjPanelCond1() {
        return jPanelCond1;
    }

    public JPanel getjPanelCond2() {
        return jPanelCond2;
    }

    public JPanel getjPanelCond3() {
        return jPanelCond3;
    }

    public JPanel getjPanelCardFechaNac() {
        return jPanelCardFechaNac;
    }

    public PacientePanelMain getPacientePanelMain() {
        return pacientePanelMain;
    }

}
