/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Util.AnimacionPNL;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.fonts.jetbrains_mono.FlatJetBrainsMonoFont;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.concurrent.atomic.AtomicBoolean;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author Administrador
 */
public class WinAppNutris extends javax.swing.JFrame {

    private HomePanel homePanel;
    private PacientePanelMain pacientePanelMain;
    private DietaPanelMain dietaPanelMain;
    private ComidaPanelMain comidaPanelMain;
    private CardLayout cardLayout;
//    private AnimacionPNL animacionPNL;

    /**
     * Creates new form WinAppNutris
     */
    public WinAppNutris() {
        initComponents();
//        animacionPNL = new AnimacionPNL(this, 10, 1, -90, new AtomicBoolean(true));
        CrearPanels();
    }

    private void CrearPanels() {
        homePanel = new HomePanel();
        pacientePanelMain = new PacientePanelMain();
        dietaPanelMain = new DietaPanelMain();
        comidaPanelMain = new ComidaPanelMain();
        PanelCenter.add(homePanel, "home");
        PanelCenter.add(pacientePanelMain, "paciente");
        PanelCenter.add(dietaPanelMain, "dieta");
        PanelCenter.add(comidaPanelMain, "comida");
        cardLayout = (CardLayout) PanelCenter.getLayout();
        cardLayout.show(PanelCenter, "home");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPpal = new javax.swing.JPanel();
        PanelCenter = new javax.swing.JPanel();
        PanelWest = new javax.swing.JPanel();
        jLabelDieta = new javax.swing.JLabel();
        jLabelPaciente = new javax.swing.JLabel();
        jLabelComida = new javax.swing.JLabel();
        jLabelHome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NUTRIS");
        setFont(new java.awt.Font("JetBrains Mono NL Medium", 0, 12)); // NOI18N
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        PanelPpal.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                PanelPpalMouseMoved(evt);
            }
        });
        PanelPpal.setLayout(new java.awt.BorderLayout());

        PanelCenter.setLayout(new java.awt.CardLayout());
        PanelPpal.add(PanelCenter, java.awt.BorderLayout.CENTER);

        PanelWest.setBackground(new java.awt.Color(62, 26, 26));
        PanelWest.setPreferredSize(new java.awt.Dimension(100, 768));

        jLabelDieta.setBackground(new java.awt.Color(62, 26, 26));
        jLabelDieta.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 16)); // NOI18N
        jLabelDieta.setText("Dieta");
        jLabelDieta.setOpaque(true);
        jLabelDieta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDietaMouseClicked(evt);
            }
        });

        jLabelPaciente.setBackground(new java.awt.Color(62, 26, 26));
        jLabelPaciente.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 16)); // NOI18N
        jLabelPaciente.setText("Paciente");
        jLabelPaciente.setOpaque(true);
        jLabelPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelPacienteMouseClicked(evt);
            }
        });

        jLabelComida.setBackground(new java.awt.Color(62, 26, 26));
        jLabelComida.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 16)); // NOI18N
        jLabelComida.setText("Comida");
        jLabelComida.setOpaque(true);
        jLabelComida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelComidaMouseClicked(evt);
            }
        });

        jLabelHome.setBackground(new java.awt.Color(62, 26, 26));
        jLabelHome.setFont(new java.awt.Font("JetBrains Mono Thin", 0, 16)); // NOI18N
        jLabelHome.setText("Home");
        jLabelHome.setOpaque(true);
        jLabelHome.setPreferredSize(new java.awt.Dimension(80, 22));
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelWestLayout = new javax.swing.GroupLayout(PanelWest);
        PanelWest.setLayout(PanelWestLayout);
        PanelWestLayout.setHorizontalGroup(
            PanelWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelWestLayout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(PanelWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelComida, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        PanelWestLayout.setVerticalGroup(
            PanelWestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelWestLayout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jLabelHome, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabelPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabelDieta, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabelComida, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        PanelPpal.add(PanelWest, java.awt.BorderLayout.WEST);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPpal, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPpal, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
//        animacionPNL = new AnimacionPNL(this, 10, 1, -90, new AtomicBoolean(true));
    }//GEN-LAST:event_formComponentResized

    private void PanelPpalMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelPpalMouseMoved
//        if(PanelWest.getX()==-90 && evt.getX()<11){
//            animacionPNL = new AnimacionPNL(this, 10, 1, 0, new AtomicBoolean(false));
//        }
//        if(PanelWest.getX()==0 && evt.getX()>100) {
//            animacionPNL = new AnimacionPNL(this, 10, 1, -90, new AtomicBoolean(true));
//        }
    }//GEN-LAST:event_PanelPpalMouseMoved

    private void jLabelPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPacienteMouseClicked
        jLabelPaciente.setBackground(new Color(30, 30, 30));
        jLabelDieta.setBackground(new Color(62,26,26));
        jLabelComida.setBackground(new Color(62,26,26));
        jLabelHome.setBackground(new Color(62,26,26));
        cardLayout.show(PanelCenter, "paciente");
    }//GEN-LAST:event_jLabelPacienteMouseClicked

    private void jLabelDietaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDietaMouseClicked
        jLabelPaciente.setBackground(new Color(62,26,26));
        jLabelDieta.setBackground(new Color(30, 30, 30));
        jLabelComida.setBackground(new Color(62,26,26));
        jLabelHome.setBackground(new Color(62,26,26));
        cardLayout.show(PanelCenter, "dieta");
    }//GEN-LAST:event_jLabelDietaMouseClicked

    private void jLabelComidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelComidaMouseClicked
        jLabelPaciente.setBackground(new Color(62,26,26));
        jLabelDieta.setBackground(new Color(62,26,26));
        jLabelComida.setBackground(new Color(30, 30, 30));
        jLabelHome.setBackground(new Color(62,26,26));
        cardLayout.show(PanelCenter, "comida");
    }//GEN-LAST:event_jLabelComidaMouseClicked

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        jLabelPaciente.setBackground(new Color(62,26,26));
        jLabelDieta.setBackground(new Color(62,26,26));
        jLabelComida.setBackground(new Color(62,26,26));
        jLabelHome.setBackground(new Color(30, 30, 30));
        cardLayout.show(PanelCenter, "home");
    }//GEN-LAST:event_jLabelHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
////            java.util.logging.Logger.getLoggjLabelDietas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(WinAppNutris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(WinAppNutris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(WinAppNutris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        FlatLaf.setPreferredMonospacedFontFamily(FlatJetBrainsMonoFont.FAMILY);
//        FlatMacDarkLaf.setup();
//        UIManager.put("Button.arc", 999);
//        UIManager.put("Component.arc", 999);
//        UIManager.put("TextComponent.arc", 999);
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new WinAppNutris().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCenter;
    private javax.swing.JPanel PanelPpal;
    private javax.swing.JPanel PanelWest;
    private javax.swing.JLabel jLabelComida;
    private javax.swing.JLabel jLabelDieta;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelPaciente;
    // End of variables declaration//GEN-END:variables

    public JPanel getPanelPpal() {
        return PanelPpal;
    }

    public JPanel getPanelWest() {
        return PanelWest;
    }

}
